In [78]:
import pandas as pd

In [79]:
import os
os.getcwd()

'c:\\Users\\hp\\Documents\\ml-based-air-quality-classification\\notebooks'

In [80]:
city_day=pd.read_csv('../data/raw/city_day.csv')

In [81]:
city_day.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [82]:
city_day.isnull().sum()

City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

In [83]:
city_day.shape

(29531, 16)

In [84]:
city_day['City'].nunique()

26

In [85]:
city_day['Date'].min(), city_day['Date'].max()

('2015-01-01', '2020-07-01')

In [86]:
city_day['AQI_Bucket'].value_counts(dropna=False)

AQI_Bucket
Moderate        8829
Satisfactory    8224
NaN             4681
Poor            2781
Very Poor       2337
Good            1341
Severe          1338
Name: count, dtype: int64

In [87]:
city_day.shape
city_day.columns.tolist()
city_day.head()
city_day.info()

<class 'pandas.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  str
 1   Date        29531 non-null  str
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  str
dtypes: float64(13), str(3)
memory usage: 3.6 MB

In [88]:
city_day[['City', 'Date', 'PM2.5', 'AQI', 'AQI_Bucket']].head(10)

        City        Date  PM2.5  AQI AQI_Bucket
0  Ahmedabad  2015-01-01    NaN  NaN        NaN
1  Ahmedabad  2015-01-02    NaN  NaN        NaN
2  Ahmedabad  2015-01-03    NaN  NaN        NaN
3  Ahmedabad  2015-01-04    NaN  NaN        NaN
4  Ahmedabad  2015-01-05    NaN  NaN        NaN
5  Ahmedabad  2015-01-06    NaN  NaN        NaN
6  Ahmedabad  2015-01-07    NaN  NaN        NaN
7  Ahmedabad  2015-01-08    NaN  NaN        NaN
8  Ahmedabad  2015-01-09    NaN  NaN        NaN
9  Ahmedabad  2015-01-10    NaN  NaN        NaN

In [89]:
city_day['City'].nunique()
city_day['City'].unique()

<StringArray>
[         'Ahmedabad',             'Aizawl',          'Amaravati',
           'Amritsar',          'Bengaluru',             'Bhopal',
       'Brajrajnagar',         'Chandigarh',            'Chennai',
         'Coimbatore',              'Delhi',          'Ernakulam',
           'Gurugram',           'Guwahati',          'Hyderabad',
             'Jaipur',         'Jorapokhar',              'Kochi',
            'Kolkata',            'Lucknow',             'Mumbai',
              'Patna',           'Shillong',            'Talcher',
 'Thiruvananthapuram',      'Visakhapatnam']
Length: 26, dtype: str

In [90]:
city_day['Date'].min(), city_day['Date'].max()

('2015-01-01', '2020-07-01')

In [91]:
city_day.groupby('City').size()

City
Ahmedabad             2009
Aizawl                 113
Amaravati              951
Amritsar              1221
Bengaluru             2009
Bhopal                 289
Brajrajnagar           938
Chandigarh             304
Chennai               2009
Coimbatore             386
Delhi                 2009
Ernakulam              162
Gurugram              1679
Guwahati               502
Hyderabad             2006
Jaipur                1114
Jorapokhar            1169
Kochi                  162
Kolkata                814
Lucknow               2009
Mumbai                2009
Patna                 1858
Shillong               310
Talcher                925
Thiruvananthapuram    1112
Visakhapatnam         1462
dtype: int64

In [92]:
city_day.isna().sum()

City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

In [93]:
city_day.groupby('City')['PM2.5'].apply(lambda x: x.isna().sum()).sort_values(ascending=False)

City
Mumbai                1225
Jorapokhar             790
Ahmedabad              628
Patna                  321
Visakhapatnam          230
Brajrajnagar           185
Talcher                184
Gurugram               154
Bengaluru              146
Amritsar               128
Chennai                117
Hyderabad              115
Lucknow                102
Shillong                64
Amaravati               59
Kolkata                 55
Thiruvananthapuram      42
Chandigarh              15
Jaipur                  12
Bhopal                   9
Coimbatore               8
Ernakulam                4
Aizawl                   2
Delhi                    2
Guwahati                 1
Kochi                    0
Name: PM2.5, dtype: int64

In [94]:
city_day.groupby('City')['PM2.5'].apply(
    lambda x: x.isna().mean() * 100
).sort_values(ascending=False)

City
Jorapokhar            67.579127
Mumbai                60.975610
Ahmedabad             31.259333
Shillong              20.645161
Talcher               19.891892
Brajrajnagar          19.722814
Patna                 17.276642
Visakhapatnam         15.731874
Amritsar              10.483210
Gurugram               9.172126
Bengaluru              7.267297
Kolkata                6.756757
Amaravati              6.203996
Chennai                5.823793
Hyderabad              5.732802
Lucknow                5.077153
Chandigarh             4.934211
Thiruvananthapuram     3.776978
Bhopal                 3.114187
Ernakulam              2.469136
Coimbatore             2.072539
Aizawl                 1.769912
Jaipur                 1.077199
Guwahati               0.199203
Delhi                  0.099552
Kochi                  0.000000
Name: PM2.5, dtype: float64

In [95]:
mumbai = city_day[city_day['City'] == 'Mumbai']

mumbai[['Date', 'PM2.5']].head(30)

             Date  PM2.5
21855  2015-01-01    NaN
21856  2015-01-02    NaN
21857  2015-01-03    NaN
21858  2015-01-04    NaN
21859  2015-01-05    NaN
21860  2015-01-06    NaN
21861  2015-01-07    NaN
21862  2015-01-08    NaN
21863  2015-01-09    NaN
21864  2015-01-10    NaN
21865  2015-01-11    NaN
21866  2015-01-12    NaN
21867  2015-01-13    NaN
21868  2015-01-14    NaN
21869  2015-01-15    NaN
21870  2015-01-16    NaN
21871  2015-01-17    NaN
21872  2015-01-18    NaN
21873  2015-01-19    NaN
21874  2015-01-20    NaN
21875  2015-01-21    NaN
21876  2015-01-22    NaN
21877  2015-01-23    NaN
21878  2015-01-24    NaN
21879  2015-01-25    NaN
21880  2015-01-26    NaN
21881  2015-01-27    NaN
21882  2015-01-28    NaN
21883  2015-01-29    NaN
21884  2015-01-30    NaN

In [96]:
mumbai = city_day[city_day['City'] == 'Mumbai']

mumbai[mumbai['PM2.5'].notna()][['Date', 'PM2.5']].head()

             Date  PM2.5
23066  2018-04-26  25.50
23076  2018-05-06  16.74
23077  2018-05-07  18.44
23078  2018-05-08  18.07
23079  2018-05-09  18.55

In [97]:
mumbai[mumbai['PM2.5'].notna()][['Date', 'PM2.5']].tail()

             Date  PM2.5
23859  2020-06-27  18.04
23860  2020-06-28  12.33
23861  2020-06-29   7.88
23862  2020-06-30   4.66
23863  2020-07-01   3.84

In [98]:
city_day.groupby('City')['Date'].agg(['min', 'max'])

                           min         max
City
Ahmedabad           2015-01-01  2020-07-01
Aizawl              2020-03-11  2020-07-01
Amaravati           2017-11-24  2020-07-01
Amritsar            2017-02-27  2020-07-01
Bengaluru           2015-01-01  2020-07-01
Bhopal              2019-09-17  2020-07-01
Brajrajnagar        2017-12-07  2020-07-01
Chandigarh          2019-09-02  2020-07-01
Chennai             2015-01-01  2020-07-01
Coimbatore          2019-06-12  2020-07-01
Delhi               2015-01-01  2020-07-01
Ernakulam           2020-01-22  2020-07-01
Gurugram            2015-11-27  2020-07-01
Guwahati            2019-02-16  2020-07-01
Hyderabad           2015-01-04  2020-07-01
Jaipur              2017-06-14  2020-07-01
Jorapokhar          2017-04-20  2020-07-01
Kochi               2020-01-22  2020-07-01
Kolkata             2018-04-10  2020-07-01
Lucknow             2015-01-01  2020-07-01
Mumbai              2015-01-01  2020-07-01
Patna               2015-06-01  2020-07-01
Shillong            2019-08-27  2020-07-01
Talcher             2017-12-20  2020-07-01
Thiruvananthapuram  2017-06-16  2020-07-01
Visakhapatnam       2016-07-01  2020-07-01

In [99]:
pm25_period = city_day.groupby('City').agg(
    first_row=('Date', 'min'),
    last_row=('Date', 'max'),
    first_pm25=('Date', lambda x: x[city_day.loc[x.index, 'PM2.5'].notna()].min()),
    last_pm25=('Date', lambda x: x[city_day.loc[x.index, 'PM2.5'].notna()].max()),
    pm25_missing=('PM2.5', lambda x: x.isna().sum()),
    total_rows=('PM2.5', 'size')
)

pm25_period['pm25_missing_pct'] = (
    pm25_period['pm25_missing'] / pm25_period['total_rows'] * 100
)

pm25_period.sort_values('pm25_missing_pct', ascending=False)

,first_row,last_row,first_pm25,last_pm25,pm25_missing,total_rows,pm25_missing_pct
City,,,,,,,
Jorapokhar,2017-04-20,2020-07-01,2019-01-09,2020-06-02,790,1169,67.579127
Mumbai,2015-01-01,2020-07-01,2018-04-26,2020-07-01,1225,2009,60.975610
Ahmedabad,2015-01-01,2020-07-01,2015-01-28,2020-07-01,628,2009,31.259333
Shillong,2019-08-27,2020-07-01,2019-08-27,2020-07-01,64,310,20.645161
Talcher,2017-12-20,2020-07-01,2018-02-07,2020-07-01,184,925,19.891892
Brajrajnagar,2017-12-07,2020-07-01,2017-12-07,2020-06-26,185,938,19.722814
Patna,2015-06-01,2020-07-01,2015-10-01,2020-07-01,321,1858,17.276642
Visakhapatnam,2016-07-01,2020-07-01,2016-07-01,2020-07-01,230,1462,15.731874
Amritsar,2017-02-27,2020-07-01,2017-02-27,2020-07-01,128,1221,10.483210
Gurugram,2015-11-27,2020-07-01,2016-01-22,2020-07-01,154,1679,9.172126
Bengaluru,2015-01-01,2020-07-01,2015-03-20,2020-07-01,146,2009,7.267297
Kolkata,2018-04-10,2020-07-01,2018-04-10,2020-07-01,55,814,6.756757
Amaravati,2017-11-24,2020-07-01,2017-11-24,2020-07-01,59,951,6.203996
Chennai,2015-01-01,2020-07-01,2015-03-23,2020-07-01,117,2009,5.823793
Hyderabad,2015-01-04,2020-07-01,2015-03-31,2020-07-01,115,2006,5.732802
Lucknow,2015-01-01,2020-07-01,2015-03-20,2020-07-01,102,2009,5.077153
Chandigarh,2019-09-02,2020-07-01,2019-09-02,2020-07-01,15,304,4.934211
Thiruvananthapuram,2017-06-16,2020-07-01,2017-06-16,2020-07-01,42,1112,3.776978
Bhopal,2019-09-17,2020-07-01,2019-09-17,2020-07-01,9,289,3.114187
Ernakulam,2020-01-22,2020-07-01,2020-01-22,2020-07-01,4,162,2.469136
Coimbatore,2019-06-12,2020-07-01,2019-06-12,2020-06-30,8,386,2.072539
Aizawl,2020-03-11,2020-07-01,2020-03-11,2020-07-01,2,113,1.769912
Jaipur,2017-06-14,2020-07-01,2017-06-19,2020-07-01,12,1114,1.077199
Guwahati,2019-02-16,2020-07-01,2019-02-16,2020-07-01,1,502,0.199203
Delhi,2015-01-01,2020-07-01,2015-01-01,2020-07-01,2,2009,0.099552
Kochi,2020-01-22,2020-07-01,2020-01-22,2020-07-01,0,162,0.000000

In [100]:
city_day['Date'] = pd.to_datetime(city_day['Date'])

def max_missing_streak(group):
    missing = group['PM2.5'].isna()
    groups = (~missing).cumsum()
    return missing.groupby(groups).sum().max()

gap_analysis = city_day.groupby('City').apply(max_missing_streak)

gap_analysis.sort_values(ascending=False)

City
Mumbai                1211
Jorapokhar             629
Ahmedabad              339
Visakhapatnam          172
Patna                  165
Hyderabad               86
Chennai                 81
Bengaluru               78
Lucknow                 78
Amritsar                60
Gurugram                56
Brajrajnagar            54
Talcher                 49
Amaravati               37
Kolkata                 31
Shillong                27
Chandigarh              14
Bhopal                   9
Thiruvananthapuram       9
Jaipur                   5
Ernakulam                2
Coimbatore               2
Delhi                    2
Aizawl                   1
Guwahati                 1
Kochi                    0
dtype: int64

In [101]:
city_day.duplicated(subset=['City', 'Date']).sum()

np.int64(0)

In [102]:
date_gaps = city_day.groupby('City')['Date'].apply(
    lambda x: x.sort_values().diff().dt.days.value_counts().head()
)

date_gaps

City                Ahmedabad
Ahmedabad           1.0          2008
Aizawl              1.0           112
Amaravati           1.0           950
Amritsar            1.0          1220
Bengaluru           1.0          2008
Bhopal              1.0           288
Brajrajnagar        1.0           937
Chandigarh          1.0           303
Chennai             1.0          2008
Coimbatore          1.0           385
Delhi               1.0          2008
Ernakulam           1.0           161
Gurugram            1.0          1678
Guwahati            1.0           501
Hyderabad           1.0          2005
Jaipur              1.0          1113
Jorapokhar          1.0          1168
Kochi               1.0           161
Kolkata             1.0           813
Lucknow             1.0          2008
Mumbai              1.0          2008
Patna               1.0          1857
Shillong            1.0           309
Talcher             1.0           924
Thiruvananthapuram  1.0          1111
Visakhapatnam       1.0          1461
Name: Date, dtype: int64

In [103]:
pollutant_cols = [
    'PM2.5', 'PM10', 'NO', 'NO2', 'NOx',
    'NH3', 'CO', 'SO2', 'O3',
    'Benzene', 'Toluene', 'Xylene'
]

(city_day[pollutant_cols] < 0).sum()

PM2.5      0
PM10       0
NO         0
NO2        0
NOx        0
NH3        0
CO         0
SO2        0
O3         0
Benzene    0
Toluene    0
Xylene     0
dtype: int64

In [104]:
(city_day[pollutant_cols] == 0).sum()

PM2.5         0
PM10          0
NO            0
NO2           0
NOx         740
NH3           0
CO         2328
SO2           0
O3            0
Benzene    3802
Toluene    2861
Xylene     1747
dtype: int64

In [105]:
city_day[pollutant_cols].describe().T[
    ['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']
]

,count,mean,std,min,25%,50%,75%,max
PM2.5,24933.0,67.450578,64.661449,0.04,28.820,48.57,80.5900,949.99
PM10,18391.0,118.127103,90.605110,0.01,56.255,95.68,149.7450,1000.00
NO,25949.0,17.574730,22.785846,0.02,5.630,9.89,19.9500,390.68
NO2,25946.0,28.560659,24.474746,0.01,11.750,21.69,37.6200,362.21
NOx,25346.0,32.309123,31.646011,0.00,12.820,23.52,40.1275,467.63
NH3,19203.0,23.483476,25.684275,0.01,8.580,15.85,30.0200,352.89
CO,27472.0,2.248598,6.962884,0.00,0.510,0.89,1.4500,175.81
SO2,25677.0,14.531977,18.133775,0.01,5.670,9.16,15.2200,193.86
O3,25509.0,34.491430,21.694928,0.01,18.860,30.84,45.5700,257.73
Benzene,23908.0,3.280840,15.811136,0.00,0.120,1.07,3.0800,455.03
Toluene,21490.0,8.700972,19.969164,0.00,0.600,2.97,9.1500,454.85
Xylene,11422.0,3.070128,6.323247,0.00,0.140,0.98,3.3500,170.37

In [106]:
city_day.nlargest(20, 'PM2.5')[
    ['City', 'Date', 'PM2.5']
]

           City       Date   PM2.5
13041  Gurugram 2017-08-29  949.99
25729  Shillong 2019-09-03  917.77
14156  Guwahati 2019-05-04  916.67
12504  Gurugram 2016-03-10  914.94
25728  Shillong 2019-09-02  914.64
12511  Gurugram 2016-03-17  894.75
3143   Amritsar 2017-05-08  868.66
13011  Gurugram 2017-07-30  858.73
3145   Amritsar 2017-05-10  832.80
12990  Gurugram 2017-07-09  821.42
12997  Gurugram 2017-07-16  812.49
19924   Lucknow 2015-03-20  742.67
12995  Gurugram 2017-07-14  723.16
10904     Delhi 2016-11-06  685.36
19926   Lucknow 2015-03-22  674.43
24066     Patna 2015-12-20  645.50
13042  Gurugram 2017-08-30  643.71
11271     Delhi 2017-11-08  639.19
12745  Gurugram 2016-11-06  616.19
3146   Amritsar 2017-05-11  595.88

In [107]:
city_day[
    (city_day['City'] == 'Gurugram') &
    (city_day['Date'] == '2017-08-29')
].T

                          13041
City                   Gurugram
Date        2017-08-29 00:00:00
PM2.5                    949.99
PM10                        NaN
NO                        26.31
NO2                       28.34
NOx                         NaN
NH3                         NaN
CO                         0.92
SO2                        7.44
O3                        29.91
Benzene                     0.0
Toluene                     0.0
Xylene                      NaN
AQI                         NaN
AQI_Bucket                  NaN

In [108]:
pakenvp = pd.read_excel("../data/raw/pakenvp.xlsx")
pakenv2act = pd.read_excel("../data/raw/pakenv2act.xlsx")

In [109]:
pakenvp.shape

(774, 19)

In [110]:
pakenvp.columns.tolist()

['Date Recorded',
 'Month',
 'Location',
 'Temp',
 'Weather',
 'Wind Speed',
 'PP',
 'Wind Dir',
 'Humidity',
 'Barometer',
 'Visibility',
 'Respirable Pariculate matter (PM10)',
 'Respirable Pariculate matter (PM2.5)',
 'Nitrogen Oxides as (NO)',
 'Nitrogen Oxides as (NO2)',
 'SulphurDioxide (SO2)',
 'Ozone (O3)',
 'Hazard Level',
 'AQI']

In [111]:
pakenvp.head()

,Date Recorded,Month,Location,Temp,Weather,Wind Speed,PP,Wind Dir,Humidity,Barometer,Visibility,Respirable Pariculate matter (PM10),Respirable Pariculate matter (PM2.5),Nitrogen Oxides as (NO),Nitrogen Oxides as (NO2),SulphurDioxide (SO2),Ozone (O3),Hazard Level,AQI
0,2017-11-14 00:00:00,11,0,17.0,Cloudy,11.0,0.0,N,0.722979,1014.0,4.0,42.0,41.0,18.0,65.0,15,13,2,115
1,2017-11-15 00:00:00,11,0,18.0,Cloudy,10.0,0.0,NaN,0.722979,1015.0,5.0,64.0,63.0,113.0,98.0,25,17,3,155
2,2017-11-16 00:00:00,11,0,15.0,Cool,11.0,0.0,N,0.746471,1016.0,4.0,42.0,41.0,18.0,65.0,15,20,2,115
3,2017-11-17 00:00:00,11,0,17.0,Clear,0.0,0.0,N,0.483750,1018.0,4.0,70.0,69.0,193.0,100.0,19,9,3,158
4,2017-11-18 00:00:00,11,0,17.0,Clear,6.0,0.0,N,0.625641,1017.0,4.0,64.0,63.0,113.0,98.0,25,13,3,155

In [112]:
pakenvp.dtypes

Date Recorded                            object
Month                                     int64
Location                                  int64
Temp                                    float64
Weather                                     str
Wind Speed                              float64
PP                                      float64
Wind Dir                                    str
Humidity                                float64
Barometer                               float64
Visibility                              float64
Respirable Pariculate matter (PM10)     float64
Respirable Pariculate matter (PM2.5)    float64
Nitrogen Oxides as (NO)                 float64
Nitrogen Oxides as (NO2)                float64
SulphurDioxide (SO2)                     object
Ozone (O3)                               object
Hazard Level                              int64
AQI                                       int64
dtype: object

In [113]:
pakenvp["Location"].value_counts()

Location
0    774
Name: count, dtype: int64

In [114]:
pakenvp["Location"].unique()

array([0])

In [115]:
pakenv2act.shape

(104, 7)

In [116]:
city_hour = pd.read_csv("../data/raw/city_hour.csv")

In [117]:
city_hour.shape
city_hour.columns.tolist()
city_hour.head()

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01 01:00:00,NaN,NaN,1.00,40.01,36.37,NaN,1.00,122.07,NaN,0.0,0.0,0.0,NaN,NaN
1,Ahmedabad,2015-01-01 02:00:00,NaN,NaN,0.02,27.75,19.73,NaN,0.02,85.90,NaN,0.0,0.0,0.0,NaN,NaN
2,Ahmedabad,2015-01-01 03:00:00,NaN,NaN,0.08,19.32,11.08,NaN,0.08,52.83,NaN,0.0,0.0,0.0,NaN,NaN
3,Ahmedabad,2015-01-01 04:00:00,NaN,NaN,0.30,16.45,9.20,NaN,0.30,39.53,153.58,0.0,0.0,0.0,NaN,NaN
4,Ahmedabad,2015-01-01 05:00:00,NaN,NaN,0.12,14.90,7.85,NaN,0.12,32.63,NaN,0.0,0.0,0.0,NaN,NaN

In [118]:
city_hour.shape

(707875, 16)

In [119]:
city_hour.columns.tolist()

['City',
 'Datetime',
 'PM2.5',
 'PM10',
 'NO',
 'NO2',
 'NOx',
 'NH3',
 'CO',
 'SO2',
 'O3',
 'Benzene',
 'Toluene',
 'Xylene',
 'AQI',
 'AQI_Bucket']

In [120]:
city_hour.shape

(707875, 16)

In [121]:
city_hour["City"].nunique()

26

In [122]:
city_hour["Datetime"].min(), city_hour["Datetime"].max()

('2015-01-01 01:00:00', '2020-07-01 00:00:00')

In [123]:
city_hour.groupby("City")["Datetime"].agg(["min", "max", "count"]).sort_values("count")

                                    min                  max  count
City
Aizawl              2020-03-11 09:00:00  2020-07-01 00:00:00   2680
Ernakulam           2020-01-22 13:00:00  2020-07-01 00:00:00   3852
Kochi               2020-01-22 11:00:00  2020-07-01 00:00:00   3854
Bhopal              2019-09-17 10:00:00  2020-07-01 00:00:00   6903
Chandigarh          2019-09-02 10:00:00  2020-07-01 00:00:00   7263
Shillong            2019-08-27 15:00:00  2020-07-01 00:00:00   7402
Coimbatore          2019-06-12 12:00:00  2020-07-01 00:00:00   9229
Guwahati            2019-02-16 23:00:00  2020-07-01 00:00:00  12002
Kolkata             2018-04-10 10:00:00  2020-07-01 00:00:00  19503
Talcher             2017-12-20 16:00:00  2020-07-01 00:00:00  22161
Brajrajnagar        2017-12-07 21:00:00  2020-07-01 00:00:00  22468
Amaravati           2017-11-24 17:00:00  2020-07-01 00:00:00  22784
Thiruvananthapuram  2017-06-16 14:00:00  2020-07-01 00:00:00  26651
Jaipur              2017-06-14 08:00:00  2020-07-01 00:00:00  26705
Jorapokhar          2017-04-20 08:00:00  2020-07-01 00:00:00  28025
Amritsar            2017-02-27 12:00:00  2020-07-01 00:00:00  29269
Visakhapatnam       2016-07-01 12:00:00  2020-07-01 00:00:00  35053
Gurugram            2015-11-27 15:00:00  2020-07-01 00:00:00  40258
Patna               2015-06-01 15:00:00  2020-07-01 00:00:00  44554
Hyderabad           2015-01-04 14:00:00  2020-07-01 00:00:00  48107
Chennai             2015-01-01 01:00:00  2020-07-01 00:00:00  48192
Delhi               2015-01-01 01:00:00  2020-07-01 00:00:00  48192
Ahmedabad           2015-01-01 01:00:00  2020-07-01 00:00:00  48192
Bengaluru           2015-01-01 01:00:00  2020-07-01 00:00:00  48192
Mumbai              2015-01-01 01:00:00  2020-07-01 00:00:00  48192
Lucknow             2015-01-01 01:00:00  2020-07-01 00:00:00  48192

In [124]:
city_hour.groupby("City")["PM2.5"].agg(
    ["count", "size"]
).sort_values("count")

                    count   size
City
Aizawl               2126   2680
Ernakulam            3431   3852
Kochi                3666   3854
Shillong             4657   7402
Bhopal               6568   6903
Chandigarh           6599   7263
Coimbatore           7508   9229
Jorapokhar           8074  28025
Guwahati            11558  12002
Talcher             14398  22161
Brajrajnagar        15395  22468
Kolkata             18061  19503
Mumbai              18184  48192
Amaravati           19233  22784
Thiruvananthapuram  22916  26651
Amritsar            24099  29269
Jaipur              26070  26705
Visakhapatnam       26157  35053
Ahmedabad           31129  48192
Patna               33051  44554
Gurugram            34114  40258
Bengaluru           43561  48192
Hyderabad           44507  48107
Chennai             44876  48192
Lucknow             45032  48192
Delhi               47817  48192

In [125]:
city_hour.groupby("City")["PM2.5"].apply(lambda x: x.isna().mean()).sort_values()

City
Delhi                 0.007781
Jaipur                0.023778
Guwahati              0.036994
Bhopal                0.048530
Kochi                 0.048780
Lucknow               0.065571
Chennai               0.068808
Kolkata               0.073937
Hyderabad             0.074833
Chandigarh            0.091422
Bengaluru             0.096095
Ernakulam             0.109294
Thiruvananthapuram    0.140145
Gurugram              0.152616
Amaravati             0.155855
Amritsar              0.176637
Coimbatore            0.186477
Aizawl                0.206716
Visakhapatnam         0.253787
Patna                 0.258181
Brajrajnagar          0.314803
Talcher               0.350300
Ahmedabad             0.354063
Shillong              0.370846
Mumbai                0.622676
Jorapokhar            0.711900
Name: PM2.5, dtype: float64

In [126]:
for city in ["Delhi", "Chandigarh", "Amritsar"]:
    temp = city_hour[city_hour["City"] == city].copy()
    temp["Datetime"] = pd.to_datetime(temp["Datetime"])

    print("\n", city)
    print(temp["Datetime"].diff().value_counts().head(10))

 Delhi
Datetime
0 days 01:00:00    48191
Name: count, dtype: int64

 Chandigarh
Datetime
0 days 01:00:00    7262
Name: count, dtype: int64

 Amritsar
Datetime
0 days 01:00:00    29268
Name: count, dtype: int64

In [127]:
city_hour.dtypes

City              str
Datetime          str
PM2.5         float64
PM10          float64
NO            float64
NO2           float64
NOx           float64
NH3           float64
CO            float64
SO2           float64
O3            float64
Benzene       float64
Toluene       float64
Xylene        float64
AQI           float64
AQI_Bucket        str
dtype: object

In [128]:
city_hour.isna().mean().sort_values(ascending=False)

Xylene        0.643940
PM10          0.419194
NH3           0.385014
Toluene       0.311647
Benzene       0.231179
PM2.5         0.204963
SO2           0.184175
O3            0.182529
AQI_Bucket    0.182349
AQI           0.182349
NOx           0.174076
NO2           0.165456
NO            0.164764
CO            0.122221
Datetime      0.000000
City          0.000000
dtype: float64

In [129]:
city_hour["PM2.5"].describe()

count    562787.000000
mean         67.622994
std          74.730496
min           0.010000
25%          26.200000
50%          46.420000
75%          79.490000
max         999.990000
Name: PM2.5, dtype: float64

In [130]:
city_hour["PM2.5"].quantile([0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99])

0.01      4.2500
0.05     10.5000
0.25     26.2000
0.50     46.4200
0.75     79.4900
0.95    201.0800
0.99    356.4256
Name: PM2.5, dtype: float64

In [131]:
(city_hour["PM2.5"] < 0).sum(), (city_hour["PM2.5"] == 0).sum()

(np.int64(0), np.int64(0))

In [132]:
city_hour.nlargest(20, "PM2.5")[["City", "Datetime", "PM2.5"]]

            City             Datetime   PM2.5
47509  Ahmedabad  2020-06-02 14:00:00  999.99
74083   Amritsar  2017-03-17 07:00:00  999.99
75293   Amritsar  2017-05-06 17:00:00  999.99
75328   Amritsar  2017-05-08 04:00:00  999.99
75329   Amritsar  2017-05-08 05:00:00  999.99
75330   Amritsar  2017-05-08 06:00:00  999.99
75331   Amritsar  2017-05-08 07:00:00  999.99
75332   Amritsar  2017-05-08 08:00:00  999.99
75333   Amritsar  2017-05-08 09:00:00  999.99
75334   Amritsar  2017-05-08 10:00:00  999.99
75335   Amritsar  2017-05-08 11:00:00  999.99
75336   Amritsar  2017-05-08 12:00:00  999.99
75337   Amritsar  2017-05-08 13:00:00  999.99
75387   Amritsar  2017-05-10 15:00:00  999.99
75388   Amritsar  2017-05-10 16:00:00  999.99
75394   Amritsar  2017-05-10 22:00:00  999.99
75395   Amritsar  2017-05-10 23:00:00  999.99
75396   Amritsar  2017-05-11 00:00:00  999.99
75401   Amritsar  2017-05-11 05:00:00  999.99
75402   Amritsar  2017-05-11 06:00:00  999.99

In [133]:
city_hour[city_hour["PM2.5"] >= 500][["City", "Datetime", "PM2.5"]].sort_values("PM2.5", ascending=False).head(30)

             City             Datetime   PM2.5
312620   Gurugram  2017-08-30 11:00:00  999.99
312619   Gurugram  2017-08-30 10:00:00  999.99
312618   Gurugram  2017-08-30 09:00:00  999.99
312617   Gurugram  2017-08-30 08:00:00  999.99
75337    Amritsar  2017-05-08 13:00:00  999.99
75336    Amritsar  2017-05-08 12:00:00  999.99
75331    Amritsar  2017-05-08 07:00:00  999.99
75330    Amritsar  2017-05-08 06:00:00  999.99
75329    Amritsar  2017-05-08 05:00:00  999.99
75328    Amritsar  2017-05-08 04:00:00  999.99
75293    Amritsar  2017-05-06 17:00:00  999.99
74083    Amritsar  2017-03-17 07:00:00  999.99
47509   Ahmedabad  2020-06-02 14:00:00  999.99
311684   Gurugram  2017-07-22 11:00:00  999.99
312615   Gurugram  2017-08-30 06:00:00  999.99
299675   Gurugram  2016-03-09 02:00:00  999.99
299530   Gurugram  2016-03-03 01:00:00  999.99
299529   Gurugram  2016-03-03 00:00:00  999.99
299700   Gurugram  2016-03-10 03:00:00  999.99
299699   Gurugram  2016-03-10 02:00:00  999.99
299698   Gurugram  2016-03-10 01:00:00  999.99
299697   Gurugram  2016-03-10 00:00:00  999.99
299696   Gurugram  2016-03-09 23:00:00  999.99
299695   Gurugram  2016-03-09 22:00:00  999.99
299694   Gurugram  2016-03-09 21:00:00  999.99
299693   Gurugram  2016-03-09 20:00:00  999.99
78817    Amritsar  2017-09-30 13:00:00  999.99
75730    Amritsar  2017-05-24 22:00:00  999.99
75729    Amritsar  2017-05-24 21:00:00  999.99
75406    Amritsar  2017-05-11 10:00:00  999.99

In [134]:
(city_hour["PM2.5"] >= 900).sum()

np.int64(500)

In [135]:
city_hour[city_hour["PM2.5"] >= 900]["City"].value_counts()

City
Gurugram     155
Patna        144
Hyderabad     98
Lucknow       33
Amritsar      29
Shillong      11
Chennai       10
Bengaluru      9
Ahmedabad      6
Guwahati       4
Delhi          1
Name: count, dtype: int64

In [136]:
city_hour.corr(numeric_only=True)["PM2.5"].sort_values(ascending=False)

PM2.5      1.000000
PM10       0.809011
AQI        0.502101
NOx        0.385622
NO         0.371014
NO2        0.303373
NH3        0.243264
Toluene    0.128568
SO2        0.124989
Xylene     0.117498
CO         0.082915
O3         0.047287
Benzene    0.034146
Name: PM2.5, dtype: float64

In [137]:
delhi = city_hour[city_hour["City"] == "Delhi"].copy()

delhi["PM2.5"].autocorr(lag=1), delhi["PM2.5"].autocorr(lag=24), delhi["PM2.5"].autocorr(lag=168)

(np.float64(0.9520169309973833),
 np.float64(0.7676812693204147),
 np.float64(0.5446886383858746))

In [138]:
city_hour.groupby("City").agg(
    rows=("PM2.5", "size"),
    pm25_available=("PM2.5", "count"),
    start=("Datetime", "min"),
    end=("Datetime", "max")
).sort_values("pm25_available", ascending=False)

,rows,pm25_available,start,end
City,,,,
Delhi,48192,47817,2015-01-01 01:00:00,2020-07-01 00:00:00
Lucknow,48192,45032,2015-01-01 01:00:00,2020-07-01 00:00:00
Chennai,48192,44876,2015-01-01 01:00:00,2020-07-01 00:00:00
Hyderabad,48107,44507,2015-01-04 14:00:00,2020-07-01 00:00:00
Bengaluru,48192,43561,2015-01-01 01:00:00,2020-07-01 00:00:00
Gurugram,40258,34114,2015-11-27 15:00:00,2020-07-01 00:00:00
Patna,44554,33051,2015-06-01 15:00:00,2020-07-01 00:00:00
Ahmedabad,48192,31129,2015-01-01 01:00:00,2020-07-01 00:00:00
Visakhapatnam,35053,26157,2016-07-01 12:00:00,2020-07-01 00:00:00
Jaipur,26705,26070,2017-06-14 08:00:00,2020-07-01 00:00:00
Amritsar,29269,24099,2017-02-27 12:00:00,2020-07-01 00:00:00
Thiruvananthapuram,26651,22916,2017-06-16 14:00:00,2020-07-01 00:00:00
Amaravati,22784,19233,2017-11-24 17:00:00,2020-07-01 00:00:00
Mumbai,48192,18184,2015-01-01 01:00:00,2020-07-01 00:00:00
Kolkata,19503,18061,2018-04-10 10:00:00,2020-07-01 00:00:00
Brajrajnagar,22468,15395,2017-12-07 21:00:00,2020-07-01 00:00:00
Talcher,22161,14398,2017-12-20 16:00:00,2020-07-01 00:00:00
Guwahati,12002,11558,2019-02-16 23:00:00,2020-07-01 00:00:00
Jorapokhar,28025,8074,2017-04-20 08:00:00,2020-07-01 00:00:00
Coimbatore,9229,7508,2019-06-12 12:00:00,2020-07-01 00:00:00
Chandigarh,7263,6599,2019-09-02 10:00:00,2020-07-01 00:00:00
Bhopal,6903,6568,2019-09-17 10:00:00,2020-07-01 00:00:00
Shillong,7402,4657,2019-08-27 15:00:00,2020-07-01 00:00:00
Kochi,3854,3666,2020-01-22 11:00:00,2020-07-01 00:00:00
Ernakulam,3852,3431,2020-01-22 13:00:00,2020-07-01 00:00:00
Aizawl,2680,2126,2020-03-11 09:00:00,2020-07-01 00:00:00

In [139]:
delhi = city_hour[city_hour["City"] == "Delhi"].copy()

delhi["PM2.5"].isna().sum()

np.int64(375)

In [140]:
delhi["PM2.5"].isna().astype(int).groupby(
    delhi["PM2.5"].isna().astype(int).diff().ne(0).cumsum()
).sum().sort_values(ascending=False).head(10)

PM2.5
36    65
38    40
32    24
24    23
20    22
6     22
34    20
62    14
10    13
64    11
Name: PM2.5, dtype: int64

In [141]:
city_quality = city_hour.groupby("City").agg(
    total_rows=("PM2.5", "size"),
    pm25_available=("PM2.5", "count")
)

city_quality["pm25_missing_pct"] = (
    1 - city_quality["pm25_available"] / city_quality["total_rows"]
) * 100

city_quality.sort_values("pm25_missing_pct")

                    total_rows  pm25_available  pm25_missing_pct
City
Delhi                    48192           47817          0.778137
Jaipur                   26705           26070          2.377832
Guwahati                 12002           11558          3.699383
Bhopal                    6903            6568          4.852962
Kochi                     3854            3666          4.878049
Lucknow                  48192           45032          6.557105
Chennai                  48192           44876          6.880810
Kolkata                  19503           18061          7.393734
Hyderabad                48107           44507          7.483318
Chandigarh                7263            6599          9.142228
Bengaluru                48192           43561          9.609479
Ernakulam                 3852            3431         10.929387
Thiruvananthapuram       26651           22916         14.014484
Gurugram                 40258           34114         15.261563
Amaravati                22784           19233         15.585499
Amritsar                 29269           24099         17.663740
Coimbatore                9229            7508         18.647741
Aizawl                    2680            2126         20.671642
Visakhapatnam            35053           26157         25.378712
Patna                    44554           33051         25.818108
Brajrajnagar             22468           15395         31.480328
Talcher                  22161           14398         35.030008
Ahmedabad                48192           31129         35.406292
Shillong                  7402            4657         37.084572
Mumbai                   48192           18184         62.267596
Jorapokhar               28025            8074         71.190009

In [142]:
def max_missing_gap(series):
    missing = series.isna().astype(int)
    groups = missing.ne(missing.shift()).cumsum()
    gaps = missing.groupby(groups).sum()
    return gaps.max()

city_gaps = city_hour.groupby("City")["PM2.5"].apply(max_missing_gap)

city_gaps.sort_values()

City
Kochi                    23
Guwahati                 39
Aizawl                   40
Delhi                    65
Coimbatore               70
Ernakulam                72
Jaipur                  123
Thiruvananthapuram      223
Bhopal                  254
Chandigarh              369
Shillong                674
Kolkata                 767
Amaravati               914
Talcher                1171
Brajrajnagar           1314
Gurugram               1349
Amritsar               1459
Bengaluru              1883
Lucknow                1886
Chennai                1957
Hyderabad              2051
Patna                  3973
Visakhapatnam          4141
Ahmedabad              8161
Jorapokhar            15104
Mumbai                29073
Name: PM2.5, dtype: int64

In [143]:
cities_check = ["Delhi", "Amritsar", "Lucknow", "Jaipur", "Ahmedabad", "Mumbai"]

for city in cities_check:
    temp = city_hour[city_hour["City"] == city].copy()

    missing = temp["PM2.5"].isna()
    groups = missing.ne(missing.shift()).cumsum()

    gaps = (
        temp.loc[missing]
        .groupby(groups[missing])
        .agg(
            start=("Datetime", "min"),
            end=("Datetime", "max"),
            hours=("Datetime", "size")
        )
        .sort_values("hours", ascending=False)
    )

    print(f"\n===== {city} =====")
    print(gaps.head(5))

===== Delhi =====
                     start                  end  hours
PM2.5
36     2017-08-11 18:00:00  2017-08-14 10:00:00     65
38     2017-08-21 07:00:00  2017-08-22 22:00:00     40
32     2017-06-14 17:00:00  2017-06-15 16:00:00     24
24     2016-09-27 17:00:00  2016-09-28 15:00:00     23
20     2016-07-23 12:00:00  2016-07-24 09:00:00     22

===== Amritsar =====
                     start                  end  hours
PM2.5
572    2018-08-21 18:00:00  2018-10-21 12:00:00   1459
570    2018-07-27 13:00:00  2018-08-21 16:00:00    604
234    2017-10-09 20:00:00  2017-10-19 09:00:00    230
278    2018-01-03 20:00:00  2018-01-12 09:00:00    206
120    2017-08-01 20:00:00  2017-08-08 12:00:00    161

===== Lucknow =====
                     start                  end  hours
PM2.5
1      2015-01-01 01:00:00  2015-03-20 14:00:00   1886
81     2016-05-12 18:00:00  2016-05-26 11:00:00    330
183    2016-08-06 13:00:00  2016-08-11 14:00:00    122
79     2016-05-09 12:00:00  2016-05-12 14:00:00     75
225    2017-06-13 09:00:00  2017-06-16 08:00:00     72

===== Jaipur =====
                     start                  end  hours
PM2.5
1      2017-06-14 08:00:00  2017-06-19 10:00:00    123
61     2017-08-16 19:00:00  2017-08-21 10:00:00    112
51     2017-07-28 17:00:00  2017-07-31 14:00:00     70
79     2017-09-25 14:00:00  2017-09-27 00:00:00     35
43     2017-07-23 02:00:00  2017-07-24 03:00:00     26

===== Ahmedabad =====
                     start                  end  hours
PM2.5
157    2016-11-04 14:00:00  2017-10-10 14:00:00   8161
99     2015-11-08 22:00:00  2016-06-27 14:00:00   5561
1      2015-01-01 01:00:00  2015-01-28 17:00:00    665
161    2017-10-11 20:00:00  2017-10-18 21:00:00    170
297    2019-05-10 12:00:00  2019-05-14 18:00:00    103

===== Mumbai =====
                     start                  end  hours
PM2.5
1      2015-01-01 01:00:00  2018-04-26 09:00:00  29073
3      2018-04-26 15:00:00  2018-05-06 11:00:00    237
383    2018-11-20 17:00:00  2018-11-22 09:00:00     41
181    2018-07-07 18:00:00  2018-07-09 09:00:00     40
369    2018-10-27 19:00:00  2018-10-29 10:00:00     40

In [144]:
city_period = city_hour.groupby("City").apply(
    lambda g: pd.Series({
        "first_valid_pm25": g.loc[g["PM2.5"].notna(), "Datetime"].min(),
        "last_valid_pm25": g.loc[g["PM2.5"].notna(), "Datetime"].max(),
        "pm25_available": g["PM2.5"].notna().sum()
    })
)

city_period["span_days"] = (
    city_period["last_valid_pm25"] -
    city_period["first_valid_pm25"]
).dt.total_seconds() / (24 * 3600)

city_period["span_years"] = city_period["span_days"] / 365.25

city_period.sort_values("span_years", ascending=False)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
city_hour["Datetime"] = pd.to_datetime(city_hour["Datetime"])

In [ ]:
city_period = city_hour.groupby("City").apply(
    lambda g: pd.Series({
        "first_valid_pm25": g.loc[g["PM2.5"].notna(), "Datetime"].min(),
        "last_valid_pm25": g.loc[g["PM2.5"].notna(), "Datetime"].max(),
        "pm25_available": g["PM2.5"].notna().sum()
    })
)

city_period["span_days"] = (
    city_period["last_valid_pm25"] -
    city_period["first_valid_pm25"]
).dt.total_seconds() / (24 * 3600)

city_period["span_years"] = city_period["span_days"] / 365.25

city_period.sort_values("span_years", ascending=False)

,first_valid_pm25,last_valid_pm25,pm25_available,span_days,span_years
City,,,,,
Delhi,2015-01-01 01:00:00,2020-07-01 00:00:00,47817,2007.958333,5.497490
Ahmedabad,2015-01-28 18:00:00,2020-07-01 00:00:00,31129,1980.250000,5.421629
Bengaluru,2015-03-20 12:00:00,2020-07-01 00:00:00,43561,1929.500000,5.282683
Lucknow,2015-03-20 15:00:00,2020-07-01 00:00:00,45032,1929.375000,5.282341
Chennai,2015-03-23 14:00:00,2020-07-01 00:00:00,44876,1926.416667,5.274241
Hyderabad,2015-03-31 01:00:00,2020-07-01 00:00:00,44507,1918.958333,5.253822
Patna,2015-10-01 13:00:00,2020-07-01 00:00:00,33051,1734.458333,4.748688
Gurugram,2016-01-22 20:00:00,2020-07-01 00:00:00,34114,1621.166667,4.438512
Visakhapatnam,2016-07-01 12:00:00,2020-07-01 00:00:00,26157,1460.500000,3.998631
Amritsar,2017-02-27 12:00:00,2020-07-01 00:00:00,24099,1219.500000,3.338809
Thiruvananthapuram,2017-06-16 14:00:00,2020-07-01 00:00:00,22916,1110.416667,3.040155
Jaipur,2017-06-19 11:00:00,2020-07-01 00:00:00,26070,1107.541667,3.032284
Amaravati,2017-11-24 17:00:00,2020-07-01 00:00:00,19233,949.291667,2.599019
Brajrajnagar,2017-12-07 21:00:00,2020-06-26 23:00:00,15395,932.083333,2.551905
Talcher,2018-02-07 11:00:00,2020-07-01 00:00:00,14398,874.541667,2.394365
Kolkata,2018-04-10 10:00:00,2020-07-01 00:00:00,18061,812.583333,2.224732
Mumbai,2018-04-26 10:00:00,2020-07-01 00:00:00,18184,796.583333,2.180926
Jorapokhar,2019-01-09 16:00:00,2020-06-02 00:00:00,8074,509.333333,1.394479
Guwahati,2019-02-16 23:00:00,2020-07-01 00:00:00,11558,500.041667,1.369039
Coimbatore,2019-06-12 12:00:00,2020-06-30 15:00:00,7508,384.125000,1.051677
Shillong,2019-08-27 15:00:00,2020-07-01 00:00:00,4657,308.375000,0.844285
Chandigarh,2019-09-02 10:00:00,2020-07-01 00:00:00,6599,302.583333,0.828428
Bhopal,2019-09-17 10:00:00,2020-07-01 00:00:00,6568,287.583333,0.787360
Kochi,2020-01-22 12:00:00,2020-07-01 00:00:00,3666,160.500000,0.439425
Ernakulam,2020-01-22 13:00:00,2020-07-01 00:00:00,3431,160.458333,0.439311
Aizawl,2020-03-11 09:00:00,2020-07-01 00:00:00,2126,111.625000,0.305613

In [ ]:
candidate_cities = [
    "Delhi",
    "Lucknow",
    "Chennai",
    "Hyderabad",
    "Bengaluru",
    "Gurugram",
    "Patna",
    "Amritsar",
    "Jaipur",
    "Visakhapatnam"
]

candidate_data = city_hour[
    city_hour["City"].isin(candidate_cities)
].copy()

candidate_data.isna().mean().sort_values() * 100

City           0.000000
Datetime       0.000000
NO2            7.847828
NO             8.061404
CO             8.513993
O3            10.084374
SO2           10.690786
AQI_Bucket    10.811732
AQI           10.811732
PM2.5         11.381907
NOx           11.578925
Benzene       14.053763
Toluene       14.653215
NH3           34.999784
PM10          45.707128
Xylene        59.933912
dtype: float64

In [ ]:
candidate_data.groupby("City")[[
    "PM2.5", "PM10", "NO", "NO2", "NOx",
    "NH3", "CO", "SO2", "O3",
    "Benzene", "Toluene", "Xylene"
]].corr()["PM2.5"].unstack().round(3)

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene
City,,,,,,,,,,,,
Amritsar,1.0,0.600,0.138,0.129,0.273,0.127,0.218,0.065,-0.059,0.190,0.374,0.270
Bengaluru,1.0,0.345,0.154,0.281,0.238,0.119,-0.002,0.064,0.082,0.044,0.012,NaN
Chennai,1.0,0.403,0.106,0.123,0.060,0.053,0.024,0.073,0.044,0.031,0.067,NaN
Delhi,1.0,0.817,0.552,0.541,0.446,0.531,0.172,0.330,0.162,0.609,0.360,0.133
Gurugram,1.0,0.827,0.140,0.083,0.274,-0.019,0.195,0.104,-0.172,-0.002,0.219,0.087
Hyderabad,1.0,0.544,0.060,0.133,0.157,0.130,0.079,0.102,0.034,0.164,0.158,0.084
Jaipur,1.0,0.658,0.351,0.339,0.364,0.210,0.185,0.120,-0.040,0.383,0.188,NaN
Lucknow,1.0,NaN,0.412,0.421,0.391,0.415,0.096,0.240,0.031,0.019,0.150,NaN
Patna,1.0,0.772,0.348,0.042,0.339,0.635,0.387,-0.068,-0.207,0.064,-0.055,0.045
Visakhapatnam,1.0,0.797,0.270,0.471,0.413,0.241,0.332,0.184,0.280,0.355,0.180,0.190

In [ ]:
delhi = city_hour[city_hour["City"] == "Delhi"].copy()
delhi = delhi.sort_values("Datetime")

for lag in [1, 3, 6, 12, 24]:
    print(
        f"Lag {lag}h:",
        delhi["PM2.5"].corr(delhi["PM2.5"].shift(lag))
    )

Lag 1h: 0.9520169309973833
Lag 3h: 0.8593354450534944
Lag 6h: 0.7355530398991811
Lag 12h: 0.6480050415276952
Lag 24h: 0.7676812693204147

In [ ]:
pollutants = [
    "PM10", "NO", "NO2", "NOx",
    "NH3", "CO", "SO2", "O3"
]

for pollutant in pollutants:
    print(f"\n{pollutant}")
    for lag in [1, 6, 24]:
        corr = delhi[pollutant].corr(delhi["PM2.5"].shift(lag))
        print(f"  Lag {lag}h: {corr:.3f}")

PM10
  Lag 1h: 0.791
  Lag 6h: 0.604
  Lag 24h: 0.640

NO
  Lag 1h: 0.507
  Lag 6h: 0.293
  Lag 24h: 0.438

NO2
  Lag 1h: 0.500
  Lag 6h: 0.362
  Lag 24h: 0.448

NOx
  Lag 1h: 0.407
  Lag 6h: 0.242
  Lag 24h: 0.352

NH3
  Lag 1h: 0.516
  Lag 6h: 0.405
  Lag 24h: 0.461

CO
  Lag 1h: 0.158
  Lag 6h: 0.096
  Lag 24h: 0.147

SO2
  Lag 1h: 0.314
  Lag 6h: 0.215
  Lag 24h: 0.259

O3
  Lag 1h: 0.177
  Lag 6h: 0.197
  Lag 24h: 0.113

In [ ]:
candidate_data.groupby("City")[
    ["PM2.5", "PM10", "NO", "NO2", "NOx",
     "NH3", "CO", "SO2", "O3",
     "Benzene", "Toluene", "Xylene"]
].apply(lambda x: x.notna().mean() * 100).round(1)

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene
City,,,,,,,,,,,,
Amritsar,82.3,87.0,85.1,87.6,71.6,88.6,87.6,75.2,84.0,77.9,76.8,76.3
Bengaluru,90.4,77.2,98.7,98.7,95.7,84.2,90.4,98.5,89.1,79.1,85.1,0.0
Chennai,93.1,12.1,97.4,97.4,97.5,73.5,97.6,97.3,96.2,81.3,81.6,0.0
Delhi,99.2,95.0,99.4,99.3,99.9,98.0,99.2,94.1,95.4,99.9,99.9,60.8
Gurugram,84.7,41.1,83.2,85.0,68.4,6.8,87.2,78.5,86.4,68.5,58.9,7.0
Hyderabad,92.5,80.2,97.1,97.1,99.1,79.8,99.2,96.1,96.9,92.9,92.6,92.6
Jaipur,97.6,97.1,97.1,97.0,89.6,96.9,98.0,97.6,97.1,96.4,95.7,0.0
Lucknow,93.4,0.0,97.2,97.3,81.8,48.0,82.8,94.5,97.2,91.1,89.0,0.0
Patna,74.2,10.2,80.3,79.9,80.5,10.2,82.0,78.7,75.6,81.3,81.3,81.3
Visakhapatnam,74.6,75.3,77.1,76.1,90.8,77.1,90.6,73.9,76.8,90.6,90.6,90.6

In [145]:
import pandas as pd

df = pd.read_csv("../data/raw/city_hour.csv")

print(df[["AQI", "AQI_Bucket"]].dropna().head(20))

       AQI AQI_Bucket
680  288.0       Poor
681  181.0   Moderate
682  182.0   Moderate
683  182.0   Moderate
684  179.0   Moderate
685  176.0   Moderate
686  173.0   Moderate
687  171.0   Moderate
688  167.0   Moderate
689  169.0   Moderate
690  172.0   Moderate
691  177.0   Moderate
692  306.0  Very Poor
693  306.0  Very Poor
694  306.0  Very Poor
695  306.0  Very Poor
696  306.0  Very Poor
697  306.0  Very Poor
698  306.0  Very Poor
699  306.0  Very Poor

In [146]:
pd.crosstab(
    pd.cut(
        df["AQI"],
        bins=[-1, 50, 100, 200, 300, 400, float("inf")],
        labels=[
            "Good",
            "Satisfactory",
            "Moderate",
            "Poor",
            "Very Poor",
            "Severe"
        ]
    ),
    df["AQI_Bucket"]
)

AQI_Bucket     Good  Moderate   Poor  Satisfactory  Severe  Very Poor
AQI
Good          38611         0      0             0       0          0
Satisfactory      0         0      0        189434       0          0
Moderate          0    198991      0             0       0          0
Poor              0         0  66654             0       0          0
Very Poor         0         0      0             0       0      57455
Severe            0         0      0             0   27650          0

In [147]:
row = df.iloc[680]

print(row)

City                    Ahmedabad
Datetime      2015-01-29 09:00:00
PM2.5                       80.47
PM10                          NaN
NO                           1.42
NO2                          21.9
NOx                         20.65
NH3                           NaN
CO                           1.42
SO2                         32.26
O3                          46.71
Benzene                       0.0
Toluene                       0.0
Xylene                       2.07
AQI                         288.0
AQI_Bucket                   Poor
Name: 680, dtype: object

In [148]:
print(df.loc[680, [
    "PM2.5",
    "PM10",
    "NO",
    "NO2",
    "NOx",
    "NH3",
    "CO",
    "SO2",
    "O3",
    "AQI",
    "AQI_Bucket"
]])

PM2.5         80.47
PM10            NaN
NO             1.42
NO2            21.9
NOx           20.65
NH3             NaN
CO             1.42
SO2           32.26
O3            46.71
AQI           288.0
AQI_Bucket     Poor
Name: 680, dtype: object

In [149]:
df[df["City"] == "Ahmedabad"][[
    "Datetime", "PM2.5", "PM10", "NO2", "SO2", "CO", "O3", "AQI", "AQI_Bucket"
]].head(20)

,Datetime,PM2.5,PM10,NO2,SO2,CO,O3,AQI,AQI_Bucket
0,2015-01-01 01:00:00,NaN,NaN,40.01,122.07,1.00,NaN,NaN,NaN
1,2015-01-01 02:00:00,NaN,NaN,27.75,85.90,0.02,NaN,NaN,NaN
2,2015-01-01 03:00:00,NaN,NaN,19.32,52.83,0.08,NaN,NaN,NaN
3,2015-01-01 04:00:00,NaN,NaN,16.45,39.53,0.30,153.58,NaN,NaN
4,2015-01-01 05:00:00,NaN,NaN,14.90,32.63,0.12,NaN,NaN,NaN
5,2015-01-01 06:00:00,NaN,NaN,15.95,29.87,0.33,64.25,NaN,NaN
6,2015-01-01 07:00:00,NaN,NaN,15.94,27.41,0.45,191.96,NaN,NaN
7,2015-01-01 08:00:00,NaN,NaN,16.66,20.92,1.03,177.21,NaN,NaN
8,2015-01-01 09:00:00,NaN,NaN,16.25,16.45,1.47,122.08,NaN,NaN
9,2015-01-01 10:00:00,NaN,NaN,13.78,15.14,2.05,NaN,NaN,NaN
10,2015-01-01 11:00:00,NaN,NaN,13.87,14.12,2.27,99.17,NaN,NaN
11,2015-01-01 12:00:00,NaN,NaN,12.87,13.26,1.73,91.67,NaN,NaN
12,2015-01-01 13:00:00,NaN,NaN,14.15,17.20,1.72,95.92,NaN,NaN
13,2015-01-01 14:00:00,NaN,NaN,15.74,18.78,1.85,NaN,NaN,NaN
14,2015-01-01 15:00:00,NaN,NaN,15.94,19.16,0.95,NaN,NaN,NaN
15,2015-01-01 16:00:00,NaN,NaN,17.28,17.83,0.87,NaN,NaN,NaN
16,2015-01-01 17:00:00,NaN,NaN,19.04,16.14,0.80,187.62,NaN,NaN
17,2015-01-01 18:00:00,NaN,NaN,21.24,11.93,0.47,NaN,NaN,NaN
18,2015-01-01 19:00:00,NaN,NaN,25.63,14.99,0.53,NaN,NaN,NaN
19,2015-01-01 20:00:00,NaN,NaN,16.22,13.66,0.47,187.42,NaN,NaN

In [150]:
pollutants = [
    "PM2.5", "PM10", "NO", "NO2", "NOx",
    "NH3", "CO", "SO2", "O3",
    "Benzene", "Toluene", "Xylene"
]

feature_audit = pd.DataFrame({
    "missing_count": df[pollutants].isna().sum(),
    "missing_%": df[pollutants].isna().mean() * 100,
    "available_%": df[pollutants].notna().mean() * 100
}).sort_values("missing_%")

print(feature_audit.round(2))

         missing_count  missing_%  available_%
CO               86517      12.22        87.78
NO              116632      16.48        83.52
NO2             117122      16.55        83.45
NOx             123224      17.41        82.59
O3              129208      18.25        81.75
SO2             130373      18.42        81.58
PM2.5           145088      20.50        79.50
Benzene         163646      23.12        76.88
Toluene         220607      31.16        68.84
NH3             272542      38.50        61.50
PM10            296737      41.92        58.08
Xylene          455829      64.39        35.61

In [151]:
candidate_sets = {
    "core": [
        "PM2.5", "NO", "NO2", "NOx", "CO", "SO2", "O3"
    ],
    "core_plus_benzene": [
        "PM2.5", "NO", "NO2", "NOx", "CO", "SO2", "O3", "Benzene"
    ],
    "core_plus_pm10": [
        "PM2.5", "PM10", "NO", "NO2", "NOx", "CO", "SO2", "O3"
    ],
    "all_reasonable": [
        "PM2.5", "PM10", "NO", "NO2", "NOx",
        "NH3", "CO", "SO2", "O3", "Benzene", "Toluene"
    ]
}

target_available = df["AQI_Bucket"].notna()

for name, features in candidate_sets.items():
    usable = target_available & df[features].notna().all(axis=1)
    
    print(f"{name}:")
    print(f"  rows with target: {target_available.sum():,}")
    print(f"  complete rows:    {usable.sum():,}")
    print(f"  retained:         {usable.mean() * 100:.2f}%")
    print()

core:
  rows with target: 578,795
  complete rows:    458,861
  retained:         64.82%

core_plus_benzene:
  rows with target: 578,795
  complete rows:    410,459
  retained:         57.98%

core_plus_pm10:
  rows with target: 578,795
  complete rows:    330,612
  retained:         46.70%

all_reasonable:
  rows with target: 578,795
  complete rows:    228,668
  retained:         32.30%

In [152]:
features = [
    "PM2.5", "PM10", "NO", "NO2", "NOx",
    "NH3", "CO", "SO2", "O3", "Benzene", "Toluene", "Xylene"
]

for feature in features:
    print(f"\n{'='*50}")
    print(feature)
    print(df.groupby("AQI_Bucket", observed=True)[feature].median())

==================================================
PM2.5
AQI_Bucket
Good             14.78
Moderate         53.50
Poor             85.71
Satisfactory     28.48
Severe          160.46
Very Poor       146.00
Name: PM2.5, dtype: float64

==================================================
PM10
AQI_Bucket
Good             30.175
Moderate        113.500
Poor            179.370
Satisfactory     59.550
Severe          347.410
Very Poor       260.460
Name: PM10, dtype: float64

==================================================
NO
AQI_Bucket
Good             3.50
Moderate         7.94
Poor             9.92
Satisfactory     6.30
Severe          23.22
Very Poor       14.28
Name: NO, dtype: float64

==================================================
NO2
AQI_Bucket
Good             9.66
Moderate        22.32
Poor            29.02
Satisfactory    16.02
Severe          53.53
Very Poor       36.19
Name: NO2, dtype: float64

==================================================
NOx
AQI_Bucket
Good             9.570
Moderate        22.230
Poor            29.545
Satisfactory    16.600
Severe          52.060
Very Poor       37.920
Name: NOx, dtype: float64

==================================================
NH3
AQI_Bucket
Good             8.400
Moderate        16.810
Poor            26.050
Satisfactory    12.570
Severe          47.900
Very Poor       34.625
Name: NH3, dtype: float64

==================================================
CO
AQI_Bucket
Good            0.37
Moderate        0.87
Poor            1.14
Satisfactory    0.69
Severe          3.27
Very Poor       1.49
Name: CO, dtype: float64

==================================================
SO2
AQI_Bucket
Good             5.96
Moderate         9.11
Poor            10.89
Satisfactory     6.52
Severe          22.02
Very Poor       12.91
Name: SO2, dtype: float64

==================================================
O3
AQI_Bucket
Good            18.01
Moderate        31.54
Poor            31.30
Satisfactory    24.23
Severe          25.38
Very Poor       28.04
Name: O3, dtype: float64

==================================================
Benzene
AQI_Bucket
Good            0.28
Moderate        1.20
Poor            1.69
Satisfactory    0.60
Severe          3.94
Very Poor       2.01
Name: Benzene, dtype: float64

==================================================
Toluene
AQI_Bucket
Good             0.98
Moderate         3.50
Poor             5.34
Satisfactory     1.67
Severe          21.42
Very Poor        5.96
Name: Toluene, dtype: float64

==================================================
Xylene
AQI_Bucket
Good            0.55
Moderate        1.40
Poor            1.19
Satisfactory    0.94
Severe          2.04
Very Poor       1.48
Name: Xylene, dtype: float64

In [153]:
features = [
    "PM2.5", "PM10", "NO", "NO2", "NOx",
    "NH3", "CO", "SO2", "O3", "Benzene", "Toluene", "Xylene"
]

median_table = df.groupby("AQI_Bucket", observed=True)[features].median().T

print(median_table.round(2))

AQI_Bucket   Good  Moderate    Poor  Satisfactory  Severe  Very Poor
PM2.5       14.78     53.50   85.71         28.48  160.46     146.00
PM10        30.18    113.50  179.37         59.55  347.41     260.46
NO           3.50      7.94    9.92          6.30   23.22      14.28
NO2          9.66     22.32   29.02         16.02   53.53      36.19
NOx          9.57     22.23   29.54         16.60   52.06      37.92
NH3          8.40     16.81   26.05         12.57   47.90      34.62
CO           0.37      0.87    1.14          0.69    3.27       1.49
SO2          5.96      9.11   10.89          6.52   22.02      12.91
O3          18.01     31.54   31.30         24.23   25.38      28.04
Benzene      0.28      1.20    1.69          0.60    3.94       2.01
Toluene      0.98      3.50    5.34          1.67   21.42       5.96
Xylene       0.55      1.40    1.19          0.94    2.04       1.48

In [156]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

temp = df[["PM2.5", "AQI_Bucket"]].dropna()

X = temp[["PM2.5"]]
y = temp["AQI_Bucket"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model = DecisionTreeClassifier(max_depth=5, random_state=42)
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Rows:", len(temp))
print("Accuracy:", accuracy_score(y_test, pred))

Rows: 547760
Accuracy: 0.5524317219220096

In [157]:
temp = df[["PM10", "AQI_Bucket"]].dropna()

X = temp[["PM10"]]
y = temp["AQI_Bucket"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model = DecisionTreeClassifier(max_depth=5, random_state=42)
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Rows:", len(temp))
print("Accuracy:", accuracy_score(y_test, pred))

Rows: 399932
Accuracy: 0.582069586307775

In [158]:
temp = df[["PM2.5", "PM10", "AQI_Bucket"]].dropna()

X = temp[["PM2.5", "PM10"]]
y = temp["AQI_Bucket"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model = DecisionTreeClassifier(max_depth=5, random_state=42)
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Rows:", len(temp))
print("Accuracy:", accuracy_score(y_test, pred))

Rows: 381538
Accuracy: 0.6038685327881742

In [159]:
features = ["PM2.5", "PM10", "NO", "NO2", "NOx"]

temp = df[features + ["AQI_Bucket"]].dropna()

X = temp[features]
y = temp["AQI_Bucket"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model = DecisionTreeClassifier(max_depth=5, random_state=42)
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Rows:", len(temp))
print("Accuracy:", accuracy_score(y_test, pred))

Rows: 353347
Accuracy: 0.6141502759303806

In [160]:
features = [
    "PM2.5", "PM10", "NO", "NO2", "NOx",
    "NH3", "CO", "SO2", "O3", "Benzene"
]

temp = df[features + ["AQI_Bucket"]].dropna()

X = temp[features]
y = temp["AQI_Bucket"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model = DecisionTreeClassifier(max_depth=5, random_state=42)
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Rows:", len(temp))
print("Accuracy:", accuracy_score(y_test, pred))

Rows: 265326
Accuracy: 0.6450646364904081