In [2]:
import numpy as np 
import pandas as pd

In [3]:
df=pd.read_csv('../data/raw/city_hour.csv')

In [ ]:

print("Dataset shape:", df.shape)

exact_duplicates = df.duplicated()

print("\nExact duplicate rows:", exact_duplicates.sum())

print(
    "Percentage of dataset:",
    round(exact_duplicates.mean() * 100, 4),
    "%"
)

# Inspecting a few examples to check  if duplicates exist
if exact_duplicates.sum() > 0:
    display(df.loc[exact_duplicates].head(10))
else:
    print("\nNo exact duplicate rows found.")

Dataset shape: (707875, 16)

Exact duplicate rows: 0
Percentage of dataset: 0.0 %

No exact duplicate rows found.

In [ ]:
# Duplicating city-timestamp audit

# Counting rows sharing the same City and Datetime
duplicate_city_time = df.duplicated(
    subset=["City", "Datetime"],
    keep=False
)

print(
    "Rows involved in duplicate City-Datetime combinations:",
    duplicate_city_time.sum()
)

print(
    "Percentage of dataset:",
    round(duplicate_city_time.mean() * 100, 4),
    "%"
)

# Counting distinct duplicated City-Datetime combinations
duplicate_groups = (
    df.loc[duplicate_city_time, ["City", "Datetime"]]
    .drop_duplicates()
)

print(
    "\nNumber of duplicated City-Datetime combinations:",
    len(duplicate_groups)
)

# Displaying examples for investigation
if not duplicate_groups.empty:
    print("\nExample duplicate combinations:")
    
    example_keys = duplicate_groups.head(10)

    examples = df.merge(
        example_keys,
        on=["City", "Datetime"],
        how="inner"
    )

    display(examples.sort_values(["City", "Datetime"]))
else:
    print("\nNo duplicate City-Datetime combinations found.")

Rows involved in duplicate City-Datetime combinations: 0
Percentage of dataset: 0.0 %

Number of duplicated City-Datetime combinations: 0

No duplicate City-Datetime combinations found.

In [6]:
# Counting negative values in pollutant columns

pollutant_cols = [
    "PM2.5",
    "PM10",
    "NO",
    "NO2",
    "NOx",
    "NH3",
    "CO",
    "SO2",
    "O3",
    "Benzene",
    "Toluene",
    "Xylene"
]

negative_counts = (
    df[pollutant_cols]
    .lt(0)
    .sum()
    .sort_values(ascending=False)
)

negative_summary = negative_counts.to_frame(
    name="Negative_Value_Count"
)

negative_summary["Percentage"] = (
    negative_summary["Negative_Value_Count"]
    / len(df)
    * 100
).round(4)

display(negative_summary)

         Negative_Value_Count  Percentage
PM2.5                       0         0.0
PM10                        0         0.0
NO                          0         0.0
NO2                         0         0.0
NOx                         0         0.0
NH3                         0         0.0
CO                          0         0.0
SO2                         0         0.0
O3                          0         0.0
Benzene                     0         0.0
Toluene                     0         0.0
Xylene                      0         0.0

In [ ]:
#  Investigating unusually high PM2.5 values

pm25 = df["PM2.5"]

print("PM2.5 observations:", pm25.notna().sum())
print("PM2.5 values equal to 999.99:", (pm25 == 999.99).sum())
print("PM2.5 values >= 900:", (pm25 >= 900).sum())
print("PM2.5 values >= 500:", (pm25 >= 500).sum())

print("\nHighest PM2.5 values:")
display(
    pm25.nlargest(15).to_frame(name="PM2.5")
)

PM2.5 observations: 562787
PM2.5 values equal to 999.99: 193
PM2.5 values >= 900: 500
PM2.5 values >= 500: 2120

Highest PM2.5 values:

        PM2.5
47509  999.99
74083  999.99
75293  999.99
75328  999.99
75329  999.99
75330  999.99
75331  999.99
75332  999.99
75333  999.99
75334  999.99
75335  999.99
75336  999.99
75337  999.99
75387  999.99
75388  999.99

In [8]:
# Distribution of PM2.5 values equal to 999.99 by city

extreme_pm25 = df[df["PM2.5"] == 999.99]

print("Rows with PM2.5 = 999.99:", len(extreme_pm25))

display(
    extreme_pm25.groupby("City")
    .size()
    .sort_values(ascending=False)
    .to_frame(name="Count")
)

Rows with PM2.5 = 999.99: 193

           Count
City
Gurugram     128
Amritsar      26
Lucknow       23
Bengaluru      8
Chennai        7
Ahmedabad      1

In [ ]:
# Inspecting records with unusually high PM2.5

extreme_pm25 = df[df["PM2.5"] == 999.99].copy()

print("Total rows with PM2.5 = 999.99:", len(extreme_pm25))

print("\nCounts by city:")
display(
    extreme_pm25.groupby("City")
    .size()
    .sort_values(ascending=False)
    .to_frame(name="Count")
)

print("\nSample records:")
display(
    extreme_pm25[
        [
            "City",
            "Datetime",
            "PM2.5",
            "PM10",
            "NO",
            "NO2",
            "NOx",
            "NH3",
            "CO",
            "SO2",
            "O3",
            "AQI",
            "AQI_Bucket",
        ]
    ].head(20)
)

Total rows with PM2.5 = 999.99: 193

Counts by city:

           Count
City
Gurugram     128
Amritsar      26
Lucknow       23
Bengaluru      8
Chennai        7
Ahmedabad      1

Sample records:

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,AQI,AQI_Bucket
47509,Ahmedabad,2020-06-02 14:00:00,999.99,NaN,1.44,36.25,18.6,NaN,0.3,18.56,NaN,226.0,Poor
74083,Amritsar,2017-03-17 07:00:00,999.99,84.24,19.24,28.49,NaN,12.23,0.0,2.10,15.78,310.0,Very Poor
75293,Amritsar,2017-05-06 17:00:00,999.99,110.21,11.61,16.73,NaN,29.76,0.0,1.47,15.61,122.0,Moderate
75328,Amritsar,2017-05-08 04:00:00,999.99,121.59,14.01,16.06,NaN,30.19,0.0,64.22,12.99,111.0,Moderate
75329,Amritsar,2017-05-08 05:00:00,999.99,114.84,13.60,16.03,NaN,30.36,0.0,42.39,14.48,110.0,Moderate
75330,Amritsar,2017-05-08 06:00:00,999.99,109.57,13.89,16.48,NaN,30.65,0.0,96.66,11.64,109.0,Moderate
75331,Amritsar,2017-05-08 07:00:00,999.99,113.44,14.70,16.49,NaN,30.79,0.0,72.33,12.06,108.0,Moderate
75332,Amritsar,2017-05-08 08:00:00,999.99,129.43,15.70,16.74,NaN,30.98,0.0,38.85,12.65,108.0,Moderate
75333,Amritsar,2017-05-08 09:00:00,999.99,134.00,15.66,16.45,NaN,30.43,0.0,14.71,13.56,109.0,Moderate
75334,Amritsar,2017-05-08 10:00:00,999.99,127.28,13.94,16.57,NaN,30.41,0.0,12.60,13.47,109.0,Moderate
75335,Amritsar,2017-05-08 11:00:00,999.99,114.23,12.72,16.01,NaN,30.48,0.0,12.56,14.64,109.0,Moderate
75336,Amritsar,2017-05-08 12:00:00,999.99,100.20,12.03,15.55,NaN,30.57,0.0,8.05,15.24,108.0,Moderate
75337,Amritsar,2017-05-08 13:00:00,999.99,89.00,12.59,15.80,NaN,30.34,0.0,7.00,15.71,108.0,Moderate
75387,Amritsar,2017-05-10 15:00:00,999.99,117.56,12.05,15.70,NaN,30.04,0.0,4.38,15.88,NaN,NaN
75388,Amritsar,2017-05-10 16:00:00,999.99,123.43,12.23,15.54,NaN,29.57,0.0,4.66,16.20,NaN,NaN
75394,Amritsar,2017-05-10 22:00:00,999.99,168.46,11.99,15.88,NaN,28.83,0.0,8.68,37.23,NaN,NaN
75395,Amritsar,2017-05-10 23:00:00,999.99,233.95,12.89,15.50,NaN,29.05,0.0,10.29,29.66,NaN,NaN
75396,Amritsar,2017-05-11 00:00:00,999.99,285.89,13.52,15.28,NaN,29.03,0.0,6.73,23.39,NaN,NaN
75401,Amritsar,2017-05-11 05:00:00,999.99,265.00,12.92,15.52,NaN,28.94,0.0,3.68,13.25,NaN,NaN
75402,Amritsar,2017-05-11 06:00:00,999.99,212.66,12.47,15.54,NaN,28.90,0.0,3.60,12.92,238.0,Poor

In [ ]:
# Verifying the total number of PM2.5 values equal to 999.99

print("Total 999.99 values:", (df["PM2.5"] == 999.99).sum())

print("\nPM2.5 values at or above 900:")
print((df["PM2.5"] >= 900).sum())

print("\nUnique values at or above 900:")
display(
    df.loc[df["PM2.5"] >= 900, "PM2.5"]
    .value_counts()
    .sort_index()
    .to_frame(name="Count")
)

Total 999.99 values: 193

PM2.5 values at or above 900:
500

Unique values at or above 900:

        Count
PM2.5
901.42      1
901.67      1
902.98      1
903.00      1
904.25      1
...       ...
994.78      1
995.00     75
996.97      1
997.93      1
999.99    193

[94 rows x 1 columns]

In [ ]:
# Investigating repeated extreme PM2.5 values

extreme_values = [999.99, 995.00]

for value in extreme_values:
    subset = df[df["PM2.5"] == value]

    print(f"\nPM2.5 = {value}")
    print("Total observations:", len(subset))

    print("\nObservations by city:")
    display(
        subset.groupby("City")
        .size()
        .sort_values(ascending=False)
        .to_frame(name="Count")
    )

    print("\nAQI_Bucket distribution:")
    display(
        subset["AQI_Bucket"]
        .value_counts(dropna=False)
        .to_frame(name="Count")
    )

PM2.5 = 999.99
Total observations: 193

Observations by city:

           Count
City
Gurugram     128
Amritsar      26
Lucknow       23
Bengaluru      8
Chennai        7
Ahmedabad      1

AQI_Bucket distribution:

              Count
AQI_Bucket
Severe           74
Very Poor        59
NaN              32
Moderate         13
Poor             12
Satisfactory      3

PM2.5 = 995.0
Total observations: 75

Observations by city:

           Count
City
Hyderabad     75

AQI_Bucket distribution:

              Count
AQI_Bucket
Severe           34
Very Poor        16
Poor             11
Moderate         10
Satisfactory      3
NaN               1

In [ ]:
# Inspecting hourly sequences of repeated extreme values

for city, value in [
    ("Gurugram", 999.99),
    ("Amritsar", 999.99),
    ("Hyderabad", 995.00),
]:
    city_df = (
        df.loc[df["City"] == city]
        .sort_values("Datetime")
        .copy()
    )

    city_df["is_target_value"] = city_df["PM2.5"].eq(value)

    # Identifying transitions into and out of sequences
    city_df["sequence_id"] = (
        city_df["is_target_value"]
        .ne(city_df["is_target_value"].shift())
        .cumsum()
    )

    sequences = (
        city_df.loc[city_df["is_target_value"]]
        .groupby("sequence_id")
        .agg(
            start_time=("Datetime", "min"),
            end_time=("Datetime", "max"),
            observations=("Datetime", "size"),
        )
        .reset_index(drop=True)
    )

    print(f"\nCity: {city} | PM2.5 = {value}")
    print("Number of separate sequences:", len(sequences))

    if not sequences.empty:
        print("\nLongest sequences:")
        display(
            sequences.sort_values(
                "observations",
                ascending=False
            ).head(10)
        )

City: Gurugram | PM2.5 = 999.99
Number of separate sequences: 31

Longest sequences:

             start_time             end_time  observations
28  2017-08-29 20:00:00  2017-08-30 11:00:00            16
2   2016-03-09 20:00:00  2016-03-10 03:00:00             8
20  2017-07-09 00:00:00  2017-07-09 06:00:00             7
19  2017-07-07 08:00:00  2017-07-07 13:00:00             6
23  2017-07-14 01:00:00  2017-07-14 06:00:00             6
11  2017-06-07 02:00:00  2017-06-07 07:00:00             6
9   2017-05-26 02:00:00  2017-05-26 06:00:00             5
27  2017-07-30 00:00:00  2017-07-30 04:00:00             5
18  2017-07-05 14:00:00  2017-07-05 18:00:00             5
15  2017-06-18 15:00:00  2017-06-18 18:00:00             4

City: Amritsar | PM2.5 = 999.99
Number of separate sequences: 10

Longest sequences:

            start_time             end_time  observations
2  2017-05-08 04:00:00  2017-05-08 13:00:00            10
4  2017-05-10 22:00:00  2017-05-11 00:00:00             3
5  2017-05-11 05:00:00  2017-05-11 07:00:00             3
7  2017-05-24 21:00:00  2017-05-24 22:00:00             2
6  2017-05-11 09:00:00  2017-05-11 10:00:00             2
3  2017-05-10 15:00:00  2017-05-10 16:00:00             2
1  2017-05-06 17:00:00  2017-05-06 17:00:00             1
0  2017-03-17 07:00:00  2017-03-17 07:00:00             1
8  2017-09-30 13:00:00  2017-09-30 13:00:00             1
9  2017-10-31 01:00:00  2017-10-31 01:00:00             1

City: Hyderabad | PM2.5 = 995.0
Number of separate sequences: 32

Longest sequences:

             start_time             end_time  observations
13  2015-06-24 06:00:00  2015-06-24 16:00:00            11
26  2016-06-16 02:00:00  2016-06-16 11:00:00            10
7   2015-06-01 19:00:00  2015-06-02 02:00:00             8
8   2015-06-02 04:00:00  2015-06-02 10:00:00             7
24  2016-06-15 14:00:00  2016-06-15 17:00:00             4
25  2016-06-15 21:00:00  2016-06-16 00:00:00             4
16  2015-08-21 13:00:00  2015-08-21 15:00:00             3
1   2015-04-14 01:00:00  2015-04-14 02:00:00             2
15  2015-08-20 13:00:00  2015-08-20 14:00:00             2
21  2015-09-04 15:00:00  2015-09-04 16:00:00             2

In [13]:
df["Datetime"] = pd.to_datetime(df["Datetime"], errors="coerce")

print("Datetime dtype:", df["Datetime"].dtype)
print("Missing timestamps after conversion:", df["Datetime"].isna().sum())

Datetime dtype: datetime64[us]
Missing timestamps after conversion: 0

In [ ]:
#  Verifying hourly continuity in the longest sequences

cases = [
    ("Gurugram", 999.99, "2017-08-29 20:00:00", "2017-08-30 11:00:00"),
    ("Amritsar", 999.99, "2017-05-08 04:00:00", "2017-05-08 13:00:00"),
    ("Hyderabad", 995.00, "2015-06-24 06:00:00", "2015-06-24 16:00:00"),
]

for city, value, start, end in cases:
    start = pd.Timestamp(start)
    end = pd.Timestamp(end)

    sequence = (
        df.loc[
            (df["City"] == city)
            & (df["PM2.5"] == value)
            & (df["Datetime"].between(start, end)),
            ["City", "Datetime", "PM2.5", "PM10", "AQI", "AQI_Bucket"]
        ]
        .sort_values("Datetime")
        .copy()
    )

    sequence["hours_since_previous"] = (
        sequence["Datetime"].diff().dt.total_seconds() / 3600
    )

    print(f"\n{city} | PM2.5 = {value}")
    print("Rows in interval:", len(sequence))
    print(
        "All timestamp gaps exactly one hour:",
        sequence["hours_since_previous"].dropna().eq(1).all()
    )

    display(sequence)

Gurugram | PM2.5 = 999.99
Rows in interval: 16
All timestamp gaps exactly one hour: True

,City,Datetime,PM2.5,PM10,AQI,AQI_Bucket,hours_since_previous
312605,Gurugram,2017-08-29 20:00:00,999.99,NaN,NaN,NaN,NaN
312606,Gurugram,2017-08-29 21:00:00,999.99,NaN,NaN,NaN,1.0
312607,Gurugram,2017-08-29 22:00:00,999.99,NaN,NaN,NaN,1.0
312608,Gurugram,2017-08-29 23:00:00,999.99,NaN,NaN,NaN,1.0
312609,Gurugram,2017-08-30 00:00:00,999.99,NaN,NaN,NaN,1.0
312610,Gurugram,2017-08-30 01:00:00,999.99,NaN,NaN,NaN,1.0
312611,Gurugram,2017-08-30 02:00:00,999.99,NaN,NaN,NaN,1.0
312612,Gurugram,2017-08-30 03:00:00,999.99,NaN,NaN,NaN,1.0
312613,Gurugram,2017-08-30 04:00:00,999.99,NaN,NaN,NaN,1.0
312614,Gurugram,2017-08-30 05:00:00,999.99,NaN,NaN,NaN,1.0
312615,Gurugram,2017-08-30 06:00:00,999.99,NaN,NaN,NaN,1.0
312616,Gurugram,2017-08-30 07:00:00,999.99,NaN,NaN,NaN,1.0
312617,Gurugram,2017-08-30 08:00:00,999.99,NaN,NaN,NaN,1.0
312618,Gurugram,2017-08-30 09:00:00,999.99,NaN,NaN,NaN,1.0
312619,Gurugram,2017-08-30 10:00:00,999.99,NaN,965.0,Severe,1.0
312620,Gurugram,2017-08-30 11:00:00,999.99,NaN,966.0,Severe,1.0

Amritsar | PM2.5 = 999.99
Rows in interval: 10
All timestamp gaps exactly one hour: True

,City,Datetime,PM2.5,PM10,AQI,AQI_Bucket,hours_since_previous
75328,Amritsar,2017-05-08 04:00:00,999.99,121.59,111.0,Moderate,NaN
75329,Amritsar,2017-05-08 05:00:00,999.99,114.84,110.0,Moderate,1.0
75330,Amritsar,2017-05-08 06:00:00,999.99,109.57,109.0,Moderate,1.0
75331,Amritsar,2017-05-08 07:00:00,999.99,113.44,108.0,Moderate,1.0
75332,Amritsar,2017-05-08 08:00:00,999.99,129.43,108.0,Moderate,1.0
75333,Amritsar,2017-05-08 09:00:00,999.99,134.00,109.0,Moderate,1.0
75334,Amritsar,2017-05-08 10:00:00,999.99,127.28,109.0,Moderate,1.0
75335,Amritsar,2017-05-08 11:00:00,999.99,114.23,109.0,Moderate,1.0
75336,Amritsar,2017-05-08 12:00:00,999.99,100.20,108.0,Moderate,1.0
75337,Amritsar,2017-05-08 13:00:00,999.99,89.00,108.0,Moderate,1.0

Hyderabad | PM2.5 = 995.0
Rows in interval: 11
All timestamp gaps exactly one hour: True

,City,Datetime,PM2.5,PM10,AQI,AQI_Bucket,hours_since_previous
353572,Hyderabad,2015-06-24 06:00:00,995.0,NaN,88.0,Satisfactory,NaN
353573,Hyderabad,2015-06-24 07:00:00,995.0,NaN,213.0,Poor,1.0
353574,Hyderabad,2015-06-24 08:00:00,995.0,NaN,311.0,Very Poor,1.0
353575,Hyderabad,2015-06-24 09:00:00,995.0,NaN,343.0,Very Poor,1.0
353576,Hyderabad,2015-06-24 10:00:00,995.0,NaN,374.0,Very Poor,1.0
353577,Hyderabad,2015-06-24 11:00:00,995.0,NaN,406.0,Severe,1.0
353578,Hyderabad,2015-06-24 12:00:00,995.0,NaN,437.0,Severe,1.0
353579,Hyderabad,2015-06-24 13:00:00,995.0,NaN,469.0,Severe,1.0
353580,Hyderabad,2015-06-24 14:00:00,995.0,NaN,500.0,Severe,1.0
353581,Hyderabad,2015-06-24 15:00:00,995.0,NaN,532.0,Severe,1.0
353582,Hyderabad,2015-06-24 16:00:00,995.0,NaN,563.0,Severe,1.0

In [ ]:
#  comparing other pollutant measurements
# when PM2.5 equals 999.99 versus ordinary PM2.5 values.

pollutant_columns = [
    "PM2.5", "PM10", "NO", "NO2", "NOx",
    "NH3", "CO", "SO2", "O3",
    "Benzene", "Toluene", "Xylene"
]

suspicious = df["PM2.5"].eq(999.99)
ordinary = df["PM2.5"].notna() & ~suspicious

comparison = pd.DataFrame({
    "999.99 readings": df.loc[suspicious, pollutant_columns].mean(),
    "Other non-missing PM2.5 readings": df.loc[ordinary, pollutant_columns].mean()
})

comparison["999.99 count"] = (
    df.loc[suspicious, pollutant_columns].count()
)

comparison["Other readings count"] = (
    df.loc[ordinary, pollutant_columns].count()
)

display(comparison.round(2))

,999.99 readings,Other non-missing PM2.5 readings,999.99 count,Other readings count
PM2.5,999.99,67.30,193,562594
PM10,147.38,119.49,26,390441
NO,12.28,17.76,188,549642
NO2,20.74,29.81,181,548267
NOx,21.06,32.65,49,526504
NH3,34.05,24.37,37,405423
CO,0.59,2.34,175,541495
SO2,7.94,13.80,184,539832
O3,23.47,35.42,180,538526
Benzene,0.43,3.30,145,485515
Toluene,2.82,9.52,135,432489
Xylene,18.91,3.59,3,209031

In [ ]:

# Making sure Datetime is in datetime format
df["Datetime"] = pd.to_datetime(df["Datetime"], errors="coerce")

# Inspecting the hours surrounding the suspicious readings
mask = (
    (df["City"] == "Amritsar") &
    (df["Datetime"] >= "2017-05-07 00:00:00") &
    (df["Datetime"] <= "2017-05-09 23:00:00")
)

df.loc[mask, ["City", "Datetime", "PM2.5", "PM10", "AQI", "AQI_Bucket"]]

           City            Datetime  PM2.5    PM10    AQI AQI_Bucket
75300  Amritsar 2017-05-07 00:00:00    NaN     NaN  124.0   Moderate
75301  Amritsar 2017-05-07 01:00:00    NaN  188.16  124.0   Moderate
75302  Amritsar 2017-05-07 02:00:00    NaN  183.86  125.0   Moderate
75303  Amritsar 2017-05-07 03:00:00    NaN  182.84  125.0   Moderate
75304  Amritsar 2017-05-07 04:00:00    NaN  182.47  125.0   Moderate
...         ...                 ...    ...     ...    ...        ...
75367  Amritsar 2017-05-09 19:00:00    NaN     NaN  138.0   Moderate
75368  Amritsar 2017-05-09 20:00:00    NaN     NaN    NaN        NaN
75369  Amritsar 2017-05-09 21:00:00    NaN     NaN    NaN        NaN
75370  Amritsar 2017-05-09 22:00:00    NaN     NaN    NaN        NaN
75371  Amritsar 2017-05-09 23:00:00    NaN     NaN    NaN        NaN

[72 rows x 6 columns]

In [17]:

mask = (
    (df["City"] == "Amritsar") &
    (df["Datetime"] >= "2017-05-08 00:00:00") &
    (df["Datetime"] <= "2017-05-09 00:00:00")
)

print(
    df.loc[mask, ["Datetime", "PM2.5", "PM10", "AQI", "AQI_Bucket"]]
    .to_string(index=False)
)

           Datetime  PM2.5   PM10   AQI AQI_Bucket
2017-05-08 00:00:00  86.13 144.19 117.0   Moderate
2017-05-08 01:00:00    NaN 138.38 116.0   Moderate
2017-05-08 02:00:00    NaN 133.50 115.0   Moderate
2017-05-08 03:00:00 337.85 127.11 113.0   Moderate
2017-05-08 04:00:00 999.99 121.59 111.0   Moderate
2017-05-08 05:00:00 999.99 114.84 110.0   Moderate
2017-05-08 06:00:00 999.99 109.57 109.0   Moderate
2017-05-08 07:00:00 999.99 113.44 108.0   Moderate
2017-05-08 08:00:00 999.99 129.43 108.0   Moderate
2017-05-08 09:00:00 999.99 134.00 109.0   Moderate
2017-05-08 10:00:00 999.99 127.28 109.0   Moderate
2017-05-08 11:00:00 999.99 114.23 109.0   Moderate
2017-05-08 12:00:00 999.99 100.20 108.0   Moderate
2017-05-08 13:00:00 999.99  89.00 108.0   Moderate
2017-05-08 14:00:00    NaN  76.34 108.0   Moderate
2017-05-08 15:00:00    NaN  68.01 107.0   Moderate
2017-05-08 16:00:00    NaN  67.28 107.0   Moderate
2017-05-08 17:00:00    NaN  73.54 107.0   Moderate
2017-05-08 18:00:00    NaN  85.39 107.0   Moderate
2017-05-08 19:00:00    NaN  95.41 107.0   Moderate
2017-05-08 20:00:00    NaN 112.32 107.0   Moderate
2017-05-08 21:00:00    NaN 142.67 108.0   Moderate
2017-05-08 22:00:00    NaN 177.19 109.0   Moderate
2017-05-08 23:00:00    NaN 195.97 111.0   Moderate
2017-05-09 00:00:00    NaN 188.23 112.0   Moderate

In [ ]:

# Counting occurrences of suspicious PM2.5 values by city
suspicious = df[df["PM2.5"].isin([999.99, 995.00])]

print("Total suspicious rows:", len(suspicious))

print("\nOccurrences by city:")
print(
    suspicious.groupby(["City", "PM2.5"])
    .size()
    .sort_values(ascending=False)
)

print("\nAQI categories for these rows:")
print(suspicious.groupby(["PM2.5", "AQI_Bucket"], dropna=False).size())

Total suspicious rows: 268

Occurrences by city:
City       PM2.5
Gurugram   999.99    128
Hyderabad  995.00     75
Amritsar   999.99     26
Lucknow    999.99     23
Bengaluru  999.99      8
Chennai    999.99      7
Ahmedabad  999.99      1
dtype: int64

AQI categories for these rows:
PM2.5   AQI_Bucket
995.00  Moderate        10
        Poor            11
        Satisfactory     3
        Severe          34
        Very Poor       16
        NaN              1
999.99  Moderate        13
        Poor            12
        Satisfactory     3
        Severe          74
        Very Poor       59
        NaN             32
dtype: int64

In [ ]:
# Converting timestamps to datetime
df["Datetime"] = pd.to_datetime(df["Datetime"], errors="coerce")

# Inspect suspicious values in chronological order
suspicious = df[df["PM2.5"].isin([999.99, 995.00])]

print(
    suspicious[["City", "Datetime", "PM2.5", "AQI", "AQI_Bucket"]]
    .sort_values(["City", "Datetime"])
    .to_string(index=False)
)

     City            Datetime  PM2.5   AQI   AQI_Bucket
Ahmedabad 2020-06-02 14:00:00 999.99 226.0         Poor
 Amritsar 2017-03-17 07:00:00 999.99 310.0    Very Poor
 Amritsar 2017-05-06 17:00:00 999.99 122.0     Moderate
 Amritsar 2017-05-08 04:00:00 999.99 111.0     Moderate
 Amritsar 2017-05-08 05:00:00 999.99 110.0     Moderate
 Amritsar 2017-05-08 06:00:00 999.99 109.0     Moderate
 Amritsar 2017-05-08 07:00:00 999.99 108.0     Moderate
 Amritsar 2017-05-08 08:00:00 999.99 108.0     Moderate
 Amritsar 2017-05-08 09:00:00 999.99 109.0     Moderate
 Amritsar 2017-05-08 10:00:00 999.99 109.0     Moderate
 Amritsar 2017-05-08 11:00:00 999.99 109.0     Moderate
 Amritsar 2017-05-08 12:00:00 999.99 108.0     Moderate
 Amritsar 2017-05-08 13:00:00 999.99 108.0     Moderate
 Amritsar 2017-05-10 15:00:00 999.99   NaN          NaN
 Amritsar 2017-05-10 16:00:00 999.99   NaN          NaN
 Amritsar 2017-05-10 22:00:00 999.99   NaN          NaN
 Amritsar 2017-05-10 23:00:00 999.99   NaN          NaN
 Amritsar 2017-05-11 00:00:00 999.99   NaN          NaN
 Amritsar 2017-05-11 05:00:00 999.99   NaN          NaN
 Amritsar 2017-05-11 06:00:00 999.99 238.0         Poor
 Amritsar 2017-05-11 07:00:00 999.99 231.0         Poor
 Amritsar 2017-05-11 09:00:00 999.99 215.0         Poor
 Amritsar 2017-05-11 10:00:00 999.99 207.0         Poor
 Amritsar 2017-05-24 21:00:00 999.99 302.0    Very Poor
 Amritsar 2017-05-24 22:00:00 999.99 348.0    Very Poor
 Amritsar 2017-09-30 13:00:00 999.99 322.0    Very Poor
 Amritsar 2017-10-31 01:00:00 999.99 354.0    Very Poor
Bengaluru 2016-12-13 06:00:00 999.99 326.0    Very Poor
Bengaluru 2016-12-13 07:00:00 999.99 359.0    Very Poor
Bengaluru 2016-12-13 08:00:00 999.99 392.0    Very Poor
Bengaluru 2017-09-01 05:00:00 999.99 266.0         Poor
Bengaluru 2017-11-29 19:00:00 999.99 134.0     Moderate
Bengaluru 2018-04-30 21:00:00 999.99 210.0         Poor
Bengaluru 2018-04-30 22:00:00 999.99 226.0         Poor
Bengaluru 2018-04-30 23:00:00 999.99 240.0         Poor
  Chennai 2017-01-10 06:00:00 999.99 306.0    Very Poor
  Chennai 2017-01-10 07:00:00 999.99 336.0    Very Poor
  Chennai 2017-01-10 08:00:00 999.99 366.0    Very Poor
  Chennai 2017-01-12 11:00:00 999.99 312.0    Very Poor
  Chennai 2017-01-13 02:00:00 999.99 389.0    Very Poor
  Chennai 2017-03-16 04:00:00 999.99 260.0         Poor
  Chennai 2017-03-16 10:00:00 999.99 409.0       Severe
 Gurugram 2016-03-03 00:00:00 999.99 422.0       Severe
 Gurugram 2016-03-03 01:00:00 999.99 445.0       Severe
 Gurugram 2016-03-09 02:00:00 999.99 319.0    Very Poor
 Gurugram 2016-03-09 03:00:00 999.99 349.0    Very Poor
 Gurugram 2016-03-09 04:00:00 999.99 378.0    Very Poor
 Gurugram 2016-03-09 20:00:00 999.99 521.0       Severe
 Gurugram 2016-03-09 21:00:00 999.99 556.0       Severe
 Gurugram 2016-03-09 22:00:00 999.99 590.0       Severe
 Gurugram 2016-03-09 23:00:00 999.99 623.0       Severe
 Gurugram 2016-03-10 00:00:00 999.99 655.0       Severe
 Gurugram 2016-03-10 01:00:00 999.99 680.0       Severe
 Gurugram 2016-03-10 02:00:00 999.99 680.0       Severe
 Gurugram 2016-03-10 03:00:00 999.99 680.0       Severe
 Gurugram 2016-03-17 21:00:00 999.99   NaN          NaN
 Gurugram 2016-03-17 22:00:00 999.99   NaN          NaN
 Gurugram 2016-03-17 23:00:00 999.99   NaN          NaN
 Gurugram 2016-08-29 15:00:00 999.99 148.0     Moderate
 Gurugram 2016-08-29 16:00:00 999.99 284.0         Poor
 Gurugram 2016-10-12 15:00:00 999.99 309.0    Very Poor
 Gurugram 2016-10-12 16:00:00 999.99 339.0    Very Poor
 Gurugram 2016-11-06 00:00:00 999.99 573.0       Severe
 Gurugram 2017-05-14 15:00:00 999.99 345.0    Very Poor
 Gurugram 2017-05-14 16:00:00 999.99 373.0    Very Poor
 Gurugram 2017-05-14 17:00:00 999.99 402.0       Severe
 Gurugram 2017-05-14 18:00:00 999.99 432.0       Severe
 Gurugram 2017-05-23 21:00:00 999.99   NaN          NaN
 Gurugram 2017-05-23 22:00:00 999.99   NaN          NaN
 Gurugram 2017-05-26 02:00:00 999.99   NaN          NaN
 Gurugram 2017-05-26 03:00:00 999.99 482.0       Severe
 Gurugram 2017-05-26 04:00:00 999.99 511.0       Severe
 Gurugram 2017-05-26 05:00:00 999.99 537.0       Severe
 Gurugram 2017-05-26 06:00:00 999.99 560.0       Severe
 Gurugram 2017-05-30 23:00:00 999.99 352.0    Very Poor
 Gurugram 2017-05-31 00:00:00 999.99 381.0    Very Poor
 Gurugram 2017-05-31 01:00:00 999.99 410.0       Severe
 Gurugram 2017-05-31 02:00:00 999.99 438.0       Severe
 Gurugram 2017-06-07 02:00:00 999.99 581.0       Severe
 Gurugram 2017-06-07 03:00:00 999.99 608.0       Severe
 Gurugram 2017-06-07 04:00:00 999.99 631.0       Severe
 Gurugram 2017-06-07 05:00:00 999.99 655.0       Severe
 Gurugram 2017-06-07 06:00:00 999.99 680.0       Severe
 Gurugram 2017-06-07 07:00:00 999.99 705.0       Severe
 Gurugram 2017-06-09 08:00:00 999.99 323.0    Very Poor
 Gurugram 2017-06-09 09:00:00 999.99 353.0    Very Poor
 Gurugram 2017-06-09 10:00:00 999.99 383.0    Very Poor
 Gurugram 2017-06-09 11:00:00 999.99 413.0       Severe
 Gurugram 2017-06-11 08:00:00 999.99 354.0    Very Poor
 Gurugram 2017-06-11 09:00:00 999.99 382.0    Very Poor
 Gurugram 2017-06-11 10:00:00 999.99 411.0       Severe
 Gurugram 2017-06-15 00:00:00 999.99 369.0    Very Poor
 Gurugram 2017-06-15 01:00:00 999.99 395.0    Very Poor
 Gurugram 2017-06-15 02:00:00 999.99 423.0       Severe
 Gurugram 2017-06-15 03:00:00 999.99 451.0       Severe
 Gurugram 2017-06-18 15:00:00 999.99 342.0    Very Poor
 Gurugram 2017-06-18 16:00:00 999.99 372.0    Very Poor
 Gurugram 2017-06-18 17:00:00 999.99 402.0       Severe
 Gurugram 2017-06-18 18:00:00 999.99 432.0       Severe
 Gurugram 2017-06-19 03:00:00 999.99 591.0       Severe
 Gurugram 2017-06-19 04:00:00 999.99 618.0       Severe
 Gurugram 2017-06-19 05:00:00 999.99 647.0       Severe
 Gurugram 2017-06-19 11:00:00 999.99 734.0       Severe
 Gurugram 2017-07-05 14:00:00 999.99 352.0    Very Poor
 Gurugram 2017-07-05 15:00:00 999.99 380.0    Very Poor
 Gurugram 2017-07-05 16:00:00 999.99 408.0       Severe
 Gurugram 2017-07-05 17:00:00 999.99 437.0       Severe
 Gurugram 2017-07-05 18:00:00 999.99 466.0       Severe
 Gurugram 2017-07-07 08:00:00 999.99 341.0    Very Poor
 Gurugram 2017-07-07 09:00:00 999.99 371.0    Very Poor
 Gurugram 2017-07-07 10:00:00 999.99 402.0       Severe
 Gurugram 2017-07-07 11:00:00 999.99 432.0       Severe
 Gurugram 2017-07-07 12:00:00 999.99 461.0       Severe
 Gurugram 2017-07-07 13:00:00 999.99 489.0       Severe
 Gurugram 2017-07-09 00:00:00 999.99 341.0    Very Poor
 Gurugram 2017-07-09 01:00:00 999.99 369.0    Very Poor
 Gurugram 2017-07-09 02:00:00 999.99 398.0    Very Poor
 Gurugram 2017-07-09 03:00:00 999.99 427.0       Severe
 Gurugram 2017-07-09 04:00:00 999.99 456.0       Severe
 Gurugram 2017-07-09 05:00:00 999.99 486.0       Severe
 Gurugram 2017-07-09 06:00:00 999.99 515.0       Severe
 Gurugram 2017-07-11 12:00:00 999.99 365.0    Very Poor
 Gurugram 2017-07-11 19:00:00 999.99 410.0       Severe
 Gurugram 2017-07-11 20:00:00 999.99 433.0       Severe
 Gurugram 2017-07-11 21:00:00 999.99 456.0       Severe
 Gurugram 2017-07-11 22:00:00 999.99 480.0       Severe
 Gurugram 2017-07-14 01:00:00 999.99 317.0    Very Poor
 Gurugram 2017-07-14 02:00:00 999.99 348.0    Very Poor
 Gurugram 2017-07-14 03:00:00 999.99 379.0    Very Poor
 Gurugram 2017-07-14 04:00:00 999.99 410.0       Severe
 Gurugram 2017-07-14 05:00:00 999.99 441.0       Severe
 Gurugram 2017-07-14 06:00:00 999.99 472.0       Severe
 Gurugram 2017-07-16 21:00:00 999.99   NaN          NaN
 Gurugram 2017-07-16 22:00:00 999.99   NaN          NaN
 Gurugram 2017-07-16 23:00:00 999.99   NaN          NaN
 Gurugram 2017-07-17 00:00:00 999.99   NaN          NaN
 Gurugram 2017-07-22 11:00:00 999.99 331.0    Very Poor
 Gurugram 2017-07-22 12:00:00 999.99 362.0    Very Poor
 Gurugram 2017-07-22 13:00:00 999.99 393.0    Very Poor
 Gurugram 2017-07-22 14:00:00 999.99 424.0       Severe
 Gurugram 2017-07-28 08:00:00 999.99 319.0    Very Poor
 Gurugram 2017-07-28 09:00:00 999.99 349.0    Very Poor
 Gurugram 2017-07-28 10:00:00 999.99 378.0    Very Poor
 Gurugram 2017-07-28 11:00:00 999.99 408.0       Severe
 Gurugram 2017-07-30 00:00:00 999.99 333.0    Very Poor
 Gurugram 2017-07-30 01:00:00 999.99 364.0    Very Poor
 Gurugram 2017-07-30 02:00:00 999.99 394.0    Very Poor
 Gurugram 2017-07-30 03:00:00 999.99 424.0       Severe
 Gurugram 2017-07-30 04:00:00 999.99 454.0       Severe
 Gurugram 2017-08-29 20:00:00 999.99   NaN          NaN
 Gurugram 2017-08-29 21:00:00 999.99   NaN          NaN
 Gurugram 2017-08-29 22:00:00 999.99   NaN          NaN
 Gurugram 2017-08-29 23:00:00 999.99   NaN          NaN
 Gurugram 2017-08-30 00:00:00 999.99   NaN          NaN
 Gurugram 2017-08-30 01:00:00 999.99   NaN          NaN
 Gurugram 2017-08-30 02:00:00 999.99   NaN          NaN
 Gurugram 2017-08-30 03:00:00 999.99   NaN          NaN
 Gurugram 2017-08-30 04:00:00 999.99   NaN          NaN
 Gurugram 2017-08-30 05:00:00 999.99   NaN          NaN
 Gurugram 2017-08-30 06:00:00 999.99   NaN          NaN
 Gurugram 2017-08-30 07:00:00 999.99   NaN          NaN
 Gurugram 2017-08-30 08:00:00 999.99   NaN          NaN
 Gurugram 2017-08-30 09:00:00 999.99   NaN          NaN
 Gurugram 2017-08-30 10:00:00 999.99 965.0       Severe
 Gurugram 2017-08-30 11:00:00 999.99 966.0       Severe
 Gurugram 2018-06-13 22:00:00 999.99 616.0       Severe
 Gurugram 2018-06-13 23:00:00 999.99 632.0       Severe
 Gurugram 2018-06-14 00:00:00 999.99 648.0       Severe
 Gurugram 2018-06-14 01:00:00 999.99 664.0       Severe
 Gurugram 2018-09-18 21:00:00 999.99 358.0    Very Poor
Hyderabad 2015-04-07 11:00:00 995.00   NaN          NaN
Hyderabad 2015-04-14 01:00:00 995.00 216.0         Poor
Hyderabad 2015-04-14 02:00:00 995.00 311.0    Very Poor
Hyderabad 2015-04-14 12:00:00 995.00 338.0    Very Poor
Hyderabad 2015-04-21 16:00:00 995.00 199.0     Moderate
Hyderabad 2015-04-23 17:00:00 995.00 209.0         Poor
Hyderabad 2015-04-29 19:00:00 995.00 221.0         Poor
Hyderabad 2015-05-13 21:00:00 995.00 176.0     Moderate
Hyderabad 2015-06-01 19:00:00 995.00 197.0     Moderate
Hyderabad 2015-06-01 20:00:00 995.00 302.0    Very Poor
Hyderabad 2015-06-01 21:00:00 995.00 332.0    Very Poor
Hyderabad 2015-06-01 22:00:00 995.00 361.0    Very Poor
Hyderabad 2015-06-01 23:00:00 995.00 391.0    Very Poor
Hyderabad 2015-06-02 00:00:00 995.00 421.0       Severe
Hyderabad 2015-06-02 01:00:00 995.00 451.0       Severe
Hyderabad 2015-06-02 02:00:00 995.00 482.0       Severe
Hyderabad 2015-06-02 04:00:00 995.00 525.0       Severe
Hyderabad 2015-06-02 05:00:00 995.00 558.0       Severe
Hyderabad 2015-06-02 06:00:00 995.00 590.0       Severe
Hyderabad 2015-06-02 07:00:00 995.00 622.0       Severe
Hyderabad 2015-06-02 08:00:00 995.00 655.0       Severe
Hyderabad 2015-06-02 09:00:00 995.00 687.0       Severe
Hyderabad 2015-06-02 10:00:00 995.00 719.0       Severe
Hyderabad 2015-06-02 12:00:00 995.00 781.0       Severe
Hyderabad 2015-06-06 22:00:00 995.00 180.0     Moderate
Hyderabad 2015-06-14 19:00:00 995.00 198.0     Moderate
Hyderabad 2015-06-22 18:00:00 995.00 197.0     Moderate
Hyderabad 2015-06-24 06:00:00 995.00  88.0 Satisfactory
Hyderabad 2015-06-24 07:00:00 995.00 213.0         Poor
Hyderabad 2015-06-24 08:00:00 995.00 311.0    Very Poor
Hyderabad 2015-06-24 09:00:00 995.00 343.0    Very Poor
Hyderabad 2015-06-24 10:00:00 995.00 374.0    Very Poor
Hyderabad 2015-06-24 11:00:00 995.00 406.0       Severe
Hyderabad 2015-06-24 12:00:00 995.00 437.0       Severe
Hyderabad 2015-06-24 13:00:00 995.00 469.0       Severe
Hyderabad 2015-06-24 14:00:00 995.00 500.0       Severe
Hyderabad 2015-06-24 15:00:00 995.00 532.0       Severe
Hyderabad 2015-06-24 16:00:00 995.00 563.0       Severe
Hyderabad 2015-08-19 18:00:00 995.00 196.0     Moderate
Hyderabad 2015-08-20 13:00:00 995.00 271.0         Poor
Hyderabad 2015-08-20 14:00:00 995.00 324.0    Very Poor
Hyderabad 2015-08-21 13:00:00 995.00 265.0         Poor
Hyderabad 2015-08-21 14:00:00 995.00 265.0         Poor
Hyderabad 2015-08-21 15:00:00 995.00 323.0    Very Poor
Hyderabad 2015-08-21 19:00:00 995.00 439.0       Severe
Hyderabad 2015-08-22 13:00:00 995.00 464.0       Severe
Hyderabad 2015-08-27 13:00:00 995.00 195.0     Moderate
Hyderabad 2015-08-28 13:00:00 995.00 239.0         Poor
Hyderabad 2015-09-04 15:00:00 995.00 304.0    Very Poor
Hyderabad 2015-09-04 16:00:00 995.00 333.0    Very Poor
Hyderabad 2015-09-05 16:00:00 995.00 260.0         Poor
Hyderabad 2015-09-26 15:00:00 995.00 264.0         Poor
Hyderabad 2016-06-15 14:00:00 995.00 194.0     Moderate
Hyderabad 2016-06-15 15:00:00 995.00 265.0         Poor
Hyderabad 2016-06-15 16:00:00 995.00 323.0    Very Poor
Hyderabad 2016-06-15 17:00:00 995.00 354.0    Very Poor
Hyderabad 2016-06-15 21:00:00 995.00 423.0       Severe
Hyderabad 2016-06-15 22:00:00 995.00 455.0       Severe
Hyderabad 2016-06-15 23:00:00 995.00 487.0       Severe
Hyderabad 2016-06-16 00:00:00 995.00 519.0       Severe
Hyderabad 2016-06-16 02:00:00 995.00 584.0       Severe
Hyderabad 2016-06-16 03:00:00 995.00 617.0       Severe
Hyderabad 2016-06-16 04:00:00 995.00 649.0       Severe
Hyderabad 2016-06-16 05:00:00 995.00 682.0       Severe
Hyderabad 2016-06-16 06:00:00 995.00 714.0       Severe
Hyderabad 2016-06-16 07:00:00 995.00 747.0       Severe
Hyderabad 2016-06-16 08:00:00 995.00 779.0       Severe
Hyderabad 2016-06-16 09:00:00 995.00 811.0       Severe
Hyderabad 2016-06-16 10:00:00 995.00 844.0       Severe
Hyderabad 2016-06-16 11:00:00 995.00 876.0       Severe
Hyderabad 2016-07-04 16:00:00 995.00 196.0     Moderate
Hyderabad 2016-07-11 12:00:00 995.00 347.0    Very Poor
Hyderabad 2016-07-11 17:00:00 995.00 411.0       Severe
Hyderabad 2016-07-22 05:00:00 995.00  99.0 Satisfactory
Hyderabad 2016-07-27 13:00:00 995.00  90.0 Satisfactory
  Lucknow 2016-06-28 15:00:00 999.99  71.0 Satisfactory
  Lucknow 2016-06-28 16:00:00 999.99  71.0 Satisfactory
  Lucknow 2016-06-28 17:00:00 999.99  69.0 Satisfactory
  Lucknow 2016-09-20 07:00:00 999.99 254.0         Poor
  Lucknow 2016-09-20 08:00:00 999.99 324.0    Very Poor
  Lucknow 2016-09-20 09:00:00 999.99 358.0    Very Poor
  Lucknow 2017-06-16 09:00:00 999.99   NaN          NaN
  Lucknow 2017-06-16 10:00:00 999.99   NaN          NaN
  Lucknow 2017-06-17 04:00:00 999.99 379.0    Very Poor
  Lucknow 2017-06-17 05:00:00 999.99 412.0       Severe
  Lucknow 2017-06-17 06:00:00 999.99 442.0       Severe
  Lucknow 2017-06-17 07:00:00 999.99 468.0       Severe
  Lucknow 2017-06-17 16:00:00 999.99 455.0       Severe
  Lucknow 2017-06-17 17:00:00 999.99 486.0       Severe
  Lucknow 2017-06-17 18:00:00 999.99 516.0       Severe
  Lucknow 2018-05-13 22:00:00 999.99 326.0    Very Poor
  Lucknow 2018-05-13 23:00:00 999.99 355.0    Very Poor
  Lucknow 2018-05-14 00:00:00 999.99 384.0    Very Poor
  Lucknow 2018-05-14 01:00:00 999.99 414.0       Severe
  Lucknow 2018-05-14 02:00:00 999.99 444.0       Severe
  Lucknow 2018-05-14 03:00:00 999.99 473.0       Severe
  Lucknow 2018-05-21 03:00:00 999.99 386.0    Very Poor
  Lucknow 2018-05-21 04:00:00 999.99 421.0       Severe

In [20]:
# Ensuring chronological order
df = df.sort_values(["City", "Datetime"]).copy()

# Calculating a 24-hour rolling average, requiring at least 16 readings
df["PM2.5_24hr_avg"] = (
    df.groupby("City")["PM2.5"]
    .transform(lambda s: s.rolling(window=24, min_periods=16).mean())
)

# Inspecting the Amritsar sequence
mask = (
    (df["City"] == "Amritsar") &
    (df["Datetime"] >= "2017-05-08 00:00:00") &
    (df["Datetime"] <= "2017-05-09 00:00:00")
)

print(
    df.loc[mask, ["Datetime", "PM2.5", "PM2.5_24hr_avg", "AQI", "AQI_Bucket"]]
    .to_string(index=False)
)

           Datetime  PM2.5  PM2.5_24hr_avg   AQI AQI_Bucket
2017-05-08 00:00:00  86.13             NaN 117.0   Moderate
2017-05-08 01:00:00    NaN             NaN 116.0   Moderate
2017-05-08 02:00:00    NaN             NaN 115.0   Moderate
2017-05-08 03:00:00 337.85             NaN 113.0   Moderate
2017-05-08 04:00:00 999.99             NaN 111.0   Moderate
2017-05-08 05:00:00 999.99             NaN 110.0   Moderate
2017-05-08 06:00:00 999.99             NaN 109.0   Moderate
2017-05-08 07:00:00 999.99             NaN 108.0   Moderate
2017-05-08 08:00:00 999.99             NaN 108.0   Moderate
2017-05-08 09:00:00 999.99             NaN 109.0   Moderate
2017-05-08 10:00:00 999.99             NaN 109.0   Moderate
2017-05-08 11:00:00 999.99             NaN 109.0   Moderate
2017-05-08 12:00:00 999.99             NaN 108.0   Moderate
2017-05-08 13:00:00 999.99             NaN 108.0   Moderate
2017-05-08 14:00:00    NaN             NaN 108.0   Moderate
2017-05-08 15:00:00    NaN             NaN 107.0   Moderate
2017-05-08 16:00:00    NaN             NaN 107.0   Moderate
2017-05-08 17:00:00    NaN             NaN 107.0   Moderate
2017-05-08 18:00:00    NaN             NaN 107.0   Moderate
2017-05-08 19:00:00    NaN             NaN 107.0   Moderate
2017-05-08 20:00:00    NaN             NaN 107.0   Moderate
2017-05-08 21:00:00    NaN             NaN 108.0   Moderate
2017-05-08 22:00:00    NaN             NaN 109.0   Moderate
2017-05-08 23:00:00    NaN             NaN 111.0   Moderate
2017-05-09 00:00:00    NaN             NaN 112.0   Moderate

In [21]:
city = "Amritsar"
start = "2017-05-08 00:00:00"
end = "2017-05-09 00:00:00"

mask = (
    (df["City"] == city) &
    (df["Datetime"] >= start) &
    (df["Datetime"] <= end)
)

cols = [
    "City", "Datetime", "PM2.5", "PM10",
    "AQI", "AQI_Bucket"
]

print(df.loc[mask, cols].to_string(index=False))

    City            Datetime  PM2.5   PM10   AQI AQI_Bucket
Amritsar 2017-05-08 00:00:00  86.13 144.19 117.0   Moderate
Amritsar 2017-05-08 01:00:00    NaN 138.38 116.0   Moderate
Amritsar 2017-05-08 02:00:00    NaN 133.50 115.0   Moderate
Amritsar 2017-05-08 03:00:00 337.85 127.11 113.0   Moderate
Amritsar 2017-05-08 04:00:00 999.99 121.59 111.0   Moderate
Amritsar 2017-05-08 05:00:00 999.99 114.84 110.0   Moderate
Amritsar 2017-05-08 06:00:00 999.99 109.57 109.0   Moderate
Amritsar 2017-05-08 07:00:00 999.99 113.44 108.0   Moderate
Amritsar 2017-05-08 08:00:00 999.99 129.43 108.0   Moderate
Amritsar 2017-05-08 09:00:00 999.99 134.00 109.0   Moderate
Amritsar 2017-05-08 10:00:00 999.99 127.28 109.0   Moderate
Amritsar 2017-05-08 11:00:00 999.99 114.23 109.0   Moderate
Amritsar 2017-05-08 12:00:00 999.99 100.20 108.0   Moderate
Amritsar 2017-05-08 13:00:00 999.99  89.00 108.0   Moderate
Amritsar 2017-05-08 14:00:00    NaN  76.34 108.0   Moderate
Amritsar 2017-05-08 15:00:00    NaN  68.01 107.0   Moderate
Amritsar 2017-05-08 16:00:00    NaN  67.28 107.0   Moderate
Amritsar 2017-05-08 17:00:00    NaN  73.54 107.0   Moderate
Amritsar 2017-05-08 18:00:00    NaN  85.39 107.0   Moderate
Amritsar 2017-05-08 19:00:00    NaN  95.41 107.0   Moderate
Amritsar 2017-05-08 20:00:00    NaN 112.32 107.0   Moderate
Amritsar 2017-05-08 21:00:00    NaN 142.67 108.0   Moderate
Amritsar 2017-05-08 22:00:00    NaN 177.19 109.0   Moderate
Amritsar 2017-05-08 23:00:00    NaN 195.97 111.0   Moderate
Amritsar 2017-05-09 00:00:00    NaN 188.23 112.0   Moderate

In [22]:
city = "Amritsar"

mask = (
    (df["City"] == city) &
    (df["Datetime"] >= "2017-05-08 04:00:00") &
    (df["Datetime"] <= "2017-05-08 13:00:00")
)

pollutants = [
    "PM2.5", "PM10", "NO", "NO2", "NOx",
    "NH3", "CO", "SO2", "O3",
    "AQI", "AQI_Bucket"
]

print(df.loc[mask, ["Datetime"] + pollutants].to_string(index=False))

           Datetime  PM2.5   PM10    NO   NO2  NOx   NH3  CO   SO2    O3   AQI AQI_Bucket
2017-05-08 04:00:00 999.99 121.59 14.01 16.06  NaN 30.19 0.0 64.22 12.99 111.0   Moderate
2017-05-08 05:00:00 999.99 114.84 13.60 16.03  NaN 30.36 0.0 42.39 14.48 110.0   Moderate
2017-05-08 06:00:00 999.99 109.57 13.89 16.48  NaN 30.65 0.0 96.66 11.64 109.0   Moderate
2017-05-08 07:00:00 999.99 113.44 14.70 16.49  NaN 30.79 0.0 72.33 12.06 108.0   Moderate
2017-05-08 08:00:00 999.99 129.43 15.70 16.74  NaN 30.98 0.0 38.85 12.65 108.0   Moderate
2017-05-08 09:00:00 999.99 134.00 15.66 16.45  NaN 30.43 0.0 14.71 13.56 109.0   Moderate
2017-05-08 10:00:00 999.99 127.28 13.94 16.57  NaN 30.41 0.0 12.60 13.47 109.0   Moderate
2017-05-08 11:00:00 999.99 114.23 12.72 16.01  NaN 30.48 0.0 12.56 14.64 109.0   Moderate
2017-05-08 12:00:00 999.99 100.20 12.03 15.55  NaN 30.57 0.0  8.05 15.24 108.0   Moderate
2017-05-08 13:00:00 999.99  89.00 12.59 15.80  NaN 30.34 0.0  7.00 15.71 108.0   Moderate

In [23]:
pollutants = [
    "PM2.5", "PM10", "NO", "NO2", "NOx",
    "NH3", "CO", "SO2", "O3",
    "Benzene", "Toluene", "Xylene"
]

for col in pollutants:
    exact_999 = (df[col] == 999.99).sum()
    exact_995 = (df[col] == 995.00).sum()

    if exact_999 > 0 or exact_995 > 0:
        print(
            f"{col}: "
            f"999.99 = {exact_999}, "
            f"995.00 = {exact_995}"
        )

PM2.5: 999.99 = 193, 995.00 = 75
PM10: 999.99 = 41, 995.00 = 0

In [24]:
df = df.sort_values(["City", "Datetime"]).copy()

df["PM2.5_24hr_count"] = (
    df.groupby("City")["PM2.5"]
    .transform(lambda s: s.rolling(window=24, min_periods=1).count())
)

mask = (
    (df["City"] == "Amritsar") &
    (df["Datetime"] >= "2017-05-08 00:00:00") &
    (df["Datetime"] <= "2017-05-09 00:00:00")
)

print(
    df.loc[
        mask,
        ["Datetime", "PM2.5", "PM2.5_24hr_count", "PM2.5_24hr_avg"]
    ].to_string(index=False)
)

           Datetime  PM2.5  PM2.5_24hr_count  PM2.5_24hr_avg
2017-05-08 00:00:00  86.13               4.0             NaN
2017-05-08 01:00:00    NaN               4.0             NaN
2017-05-08 02:00:00    NaN               4.0             NaN
2017-05-08 03:00:00 337.85               5.0             NaN
2017-05-08 04:00:00 999.99               6.0             NaN
2017-05-08 05:00:00 999.99               7.0             NaN
2017-05-08 06:00:00 999.99               8.0             NaN
2017-05-08 07:00:00 999.99               9.0             NaN
2017-05-08 08:00:00 999.99              10.0             NaN
2017-05-08 09:00:00 999.99              11.0             NaN
2017-05-08 10:00:00 999.99              12.0             NaN
2017-05-08 11:00:00 999.99              13.0             NaN
2017-05-08 12:00:00 999.99              14.0             NaN
2017-05-08 13:00:00 999.99              15.0             NaN
2017-05-08 14:00:00    NaN              15.0             NaN
2017-05-08 15:00:00    NaN              15.0             NaN
2017-05-08 16:00:00    NaN              15.0             NaN
2017-05-08 17:00:00    NaN              15.0             NaN
2017-05-08 18:00:00    NaN              15.0             NaN
2017-05-08 19:00:00    NaN              15.0             NaN
2017-05-08 20:00:00    NaN              15.0             NaN
2017-05-08 21:00:00    NaN              14.0             NaN
2017-05-08 22:00:00    NaN              13.0             NaN
2017-05-08 23:00:00    NaN              12.0             NaN
2017-05-09 00:00:00    NaN              11.0             NaN

In [25]:
mask = (
    (df["City"] == "Amritsar") &
    (df["Datetime"] >= "2017-05-07 00:00:00") &
    (df["Datetime"] <= "2017-05-08 03:00:00")
)

print(
    df.loc[
        mask,
        ["Datetime", "PM2.5", "PM2.5_24hr_count", "PM2.5_24hr_avg"]
    ].to_string(index=False)
)

           Datetime  PM2.5  PM2.5_24hr_count  PM2.5_24hr_avg
2017-05-07 00:00:00    NaN              11.0             NaN
2017-05-07 01:00:00    NaN              11.0             NaN
2017-05-07 02:00:00    NaN              11.0             NaN
2017-05-07 03:00:00    NaN              10.0             NaN
2017-05-07 04:00:00    NaN               9.0             NaN
2017-05-07 05:00:00    NaN               8.0             NaN
2017-05-07 06:00:00    NaN               7.0             NaN
2017-05-07 07:00:00    NaN               6.0             NaN
2017-05-07 08:00:00    NaN               5.0             NaN
2017-05-07 09:00:00    NaN               4.0             NaN
2017-05-07 10:00:00    NaN               4.0             NaN
2017-05-07 11:00:00    NaN               4.0             NaN
2017-05-07 12:00:00    NaN               4.0             NaN
2017-05-07 13:00:00    NaN               4.0             NaN
2017-05-07 14:00:00    NaN               4.0             NaN
2017-05-07 15:00:00    NaN               3.0             NaN
2017-05-07 16:00:00    NaN               2.0             NaN
2017-05-07 17:00:00    NaN               1.0             NaN
2017-05-07 18:00:00    NaN               0.0             NaN
2017-05-07 19:00:00    NaN               0.0             NaN
2017-05-07 20:00:00    NaN               0.0             NaN
2017-05-07 21:00:00 122.91               1.0             NaN
2017-05-07 22:00:00 105.67               2.0             NaN
2017-05-07 23:00:00  87.88               3.0             NaN
2017-05-08 00:00:00  86.13               4.0             NaN
2017-05-08 01:00:00    NaN               4.0             NaN
2017-05-08 02:00:00    NaN               4.0             NaN
2017-05-08 03:00:00 337.85               5.0             NaN